### ISSUE TITLE
Fresh install of L5.5 - 'npm run dev' crashes

### ISSUE THREAD

**Issue by ohnotnow** [JeffreyWay/laravel-mix#1168] opened 2017-09-06 12:02 UTC
- Laravel Mix Version: #.#.# (`npm list --depth=0`)

laravel-mix@1.4.2

- Node Version (`node -v`): 

8.4.0

- NPM Version (`npm -v`): 

5.4.0

- OS: 

MacOS 10.12.6

### Description:

`npm run dev` seems to compile assests, but crashes while running.  I've tried force clearing the npm cache, grabbing the latest package.json from the Laravel repo etc.

### Steps To Reproduce:

`laravel new testeroo && cd testeroo && npm install && npm run dev`

(but essentially the `npm run dev` section)

### Produces 

```

> @ dev /Users/ohffs/Documents/code/testeroo
> npm run development


> @ development /Users/ohffs/Documents/code/testeroo
> cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                 p
 DONE  Compiled successfully in 3679ms                                  12:50:13

internal/child_process.js:325
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at _errnoException (util.js:1041:11)
    at ChildProcess.spawn (internal/child_process.js:325:11)
    at exports.spawn (child_process.js:493:9)
    at Object.exports.execFile (child_process.js:208:15)
    at Object.module.exports.fileCommand (/Users/ohffs/Documents/code/testeroo/node_modules/node-notifier/lib/utils.js:53:13)
    at NotificationCenter.notify (/Users/ohffs/Documents/code/testeroo/node_modules/node-notifier/notifiers/notificationcenter.js:66:11)
    at module.exports.WebpackNotifierPlugin.compilationDone (/Users/ohffs/Documents/code/testeroo/node_modules/webpack-notifier/index.js:62:18)
    at Compiler.applyPlugins (/Users/ohffs/Documents/code/testeroo/node_modules/tapable/lib/Tapable.js:61:14)
    at emitRecords.err (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:268:11)
    at Compiler.emitRecords (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:375:38)
    at emitAssets.err (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:262:10)
    at applyPluginsAsyncSeries1.err (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:368:12)
    at next (/Users/ohffs/Documents/code/testeroo/node_modules/tapable/lib/Tapable.js:218:11)
    at Compiler.compiler.plugin (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/performance/SizeLimitsPlugin.js:99:4)
    at Compiler.applyPluginsAsyncSeries1 (/Users/ohffs/Documents/code/testeroo/node_modules/tapable/lib/Tapable.js:222:13)
    at Compiler.afterEmit (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:365:9)
    at require.forEach.err (/Users/ohffs/Documents/code/testeroo/node_modules/webpack/lib/Compiler.js:354:15)
    at /Users/ohffs/Documents/code/testeroo/node_modules/async/dist/async.js:421:16
    at iteratorCallback (/Users/ohffs/Documents/code/testeroo/node_modules/async/dist/async.js:998:13)
    at /Users/ohffs/Documents/code/testeroo/node_modules/async/dist/async.js:906:16
    at /Users/ohffs/Documents/code/testeroo/node_modules/graceful-fs/graceful-fs.js:43:10
    at FSReqWrap.oncomplete (fs.js:135:15)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ development: `cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ development script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ohffs/.npm/_logs/2017-09-06T11_50_13_970Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ dev: `npm run development`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the @ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/ohffs/.npm/_logs/2017-09-06T11_50_14_005Z-debug.log

```

**Comment by ruchern** [comment] 2017-09-06 13:05
Related and duplicate of #1065

**Comment by ohnotnow** [comment] 2017-09-06 14:19
@ruchern ah - sorry, didn't see that dup! it's been a long day.... ;-)

**Comment by ruchern** [comment] 2017-09-06 15:14
@ohnotnow I was just doing the referencing.

**Comment by ruchern** [comment] 2017-09-07 01:02
Related issue fixed. https://github.com/JeffreyWay/laravel-mix/issues/1065#issuecomment-327652555

**Closed** 2017-09-27 13:37 UTC
