### ISSUE TITLE
using on windows path separator goes bananas

### ISSUE THREAD

**Issue by MordiSacks** [JeffreyWay/laravel-mix#1329] opened 2017-11-19 15:03 UTC
- Laravel Mix Version: 1.6.1
- Node Version (`node -v`):  6.11.2
- NPM Version (`npm -v`):  3.10.10
- OS: 

### Description:
When using laravel-mix **standalone** on windows (10)  the following weirdness happens
if I run npm run production I get error

> Error: ENOENT: no such file or directory, open 'C:\Users\mordi\PhpstormProjects\IST\wp-content\themes\IST\pp.js'

npm run dev works fine, but the mix-manifest.json looks like so
```json
{
    "/pp.js": "/pp.js",
    "/endor.css": "/endor.css",
    "/pp.css": "/pp.css"
}
```

Of course my files are called
* app.js
* vendor.css
* app.css

### Steps To Reproduce:
1. Use windows 10.
2. Create a new laravel-mix standalone project.
3. Modify your package.json file like so and copy setup file to root.
```json
{
  "name": "mix",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "scripts": {
    "dev": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "hot": "cross-env NODE_ENV=development webpack-dev-server --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
  "dependencies": {
    "cross-env": "^5.1.1",
    "laravel-mix": "^1.6.1"
  }
}
```
4. Edit your webpack.mix.js like so
```js
let mix = require('laravel-mix');

/**
 * Added to fix hanging issue (webpack hangs at 95%)
 * @link https://github.com/JeffreyWay/laravel-mix/issues/1126#issuecomment-325581328
 */
mix.setPublicPath('../');

mix
    .js('js/app.js', '../')
    .sass('sass/vendor.scss', '../')
    .sass('sass/app.scss', '../')
;

if (!mix.inProduction()) {
    mix.sourceMaps();
} else {
    mix.version();
}
```
5. Create files obviously.
6. Run `npm run production`

I tried using `path.sep` insted of /,
but then the inverse happend, `npm run production` worked (without creating mix-manifest.json), and `npm run dev` did not.

as a side not, when using within laravel 5.5 it works fine.
Thank you.

**Comment by ruchern** [comment] 2017-11-22 06:53
I cannot confirm if the npm version that you are using is causing this problem. npm v3 is already very outdated. Do you mind updating and see if the issue is resolved?

`npm i -g npm@latest`

**Comment by JeffreyWay** [comment] 2018-01-17 19:26
Fixed in recent commit.

**Closed by JeffreyWay** 2018-01-17 19:26 UTC
