### ISSUE TITLE
mix.minify() doesn't minify!

### ISSUE THREAD

**Issue by andy-hammond** [JeffreyWay/laravel-mix#1295] opened 2017-10-31 19:09 UTC
- Laravel Mix Version: 1.5.1 (`npm list --depth=0`)
- Node Version (`node -v`): 6.11.2
- NPM Version (`npm -v`): 3.10.10
- OS: Windows 10

I just get an index.min.js file that is slightly larger than the 'unminified' one.

```
const {mix} = require('laravel-mix');

mix.js('resources/assets/js/index.js', 'public/js')
    .sass('resources/assets/scss/styles.scss','public/css', {
        outputStyle: 'compressed'
    })
      
if(process.env.NODE_ENV.trim() === 'production'){
    mix.minify('public/js/index.js')
    mix.version();
} else {
    mix.browserSync({
        proxy: 'http://localhost:8000'
    });
}
```

**Comment by JeffreyWay** [comment] 2017-10-31 19:27
First, you don't need to do that check for production mode. 

Minification will only take place during production builds (`npm run production`).

**Comment by the94air** [comment] 2017-11-05 09:27
I do have the same issue when using the stand alone version also using `npm run production`

**Comment by JeffreyWay** [comment] 2017-11-06 19:06
@andy-hammond I tried this out myself, and can't reproduce. So without more information, I'm going to close this.

**Closed by JeffreyWay** 2017-11-06 19:06 UTC

**Comment by kiwina** [comment] 2018-01-07 05:59
same here it does create the min version but it dosn't actually minify the file

**Comment by the94air** [comment] 2018-01-07 18:44
I solved the issue by reinstalling the dependencies (deleting this `node_modules` folder and `npm install`). It happens because I installed the dependencies with Windows and I got them compiled with Ubuntu `npm run production` and I ended up with unminified files.

**Comment by joshuaajones** [comment] 2018-01-17 19:40
Confirmed fix with a clean `npm install` and `npm run prod` on Windows

**Comment by the94air** [comment] 2018-01-17 20:08
:smile: See ....

**Comment by nezaboravi** [comment] 2018-01-19 08:31
yeah does not minify for me as well, actually it makes it bigger regarding to console output:
Here is the screenshot
https://cl.ly/3Z0V361q3z2q

**Comment by rohitbhirud** [comment] 2018-02-16 11:32
minification isn't working even after deleting node_modules and npm install.
my fix was to install cross-env & then i adding it to scripts before NODE_ENV.

**Comment by ivansammartino** [comment] 2018-02-19 14:33
Me too, the following code creates both `custom.css` and `custom.min.css` but they have the same size (and none of them is minified)

```
mix.sass('resources/assets/back/custom/sass/custom.scss', 'public/assets/back/custom.css')
    .minify('public/assets/back/custom.css');
```

If it can help, it happens on Windows 10 (Laragon as development environment)

**Comment by uzwebline** [comment] 2018-07-27 08:03
Once again, the minification will only take place during a production build. (export NODE_ENV=production).

**Comment by MFFoX** [comment] 2018-08-22 18:14
Adding to what @rohitbhirud has said, my problem was with the `NODE_ENV` not being set properly because of the scripts not being platform independent. I fixed this by using the cross-env package ie within your package.json scripts:

```
"scripts": {
    "development": "cross-env NODE_ENV=development webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  }

**Comment by the94air** [comment] 2018-09-02 08:39
Thanks, @MFFoX. I was missing the `cross-env` package on all of my scripts. I can confirm that your solution is 💯working.
