### ISSUE TITLE
[6.x] Dynamic Vue components not importing 

### ISSUE THREAD

**Issue by mattkingshott** [JeffreyWay/laravel-mix#2516] opened 2020-10-05 14:31 UTC
### Setup:

-   Laravel Mix Version: v6.0.0-beta-3
-   Node Version: v14.13.0
-   NPM Version: v6.14.8
-   OS: macOS Catalina v10.15.6

### Description:

I am using a CDN build of Vue v3.0.0 (not sure if this is relevant or not, but it is the global build).

Previously (Mix v5 & Vue v2), I was registering global Vue components in the following way within my `app.js` file:

```javascript
Vue.component('v-button', () => import(/* webpackChunkName:'js/button' */ '../vue/components/button.vue'));
```

Then within my `webpack.mix.js` file, I would use the following:

```javascript
mix.webpackConfig({
    resolve      : { symlinks: false },
    watchOptions : { ignored: /node_modules/ },
    output       : { publicPath: '/', chunkFilename: '[name].js?[hash]' },
});

mix.js('resources/js/app.js', 'public/js');
```

However, this no longer works in Mix v6 / Vue v3. 

Instead, I've adjusted the code to account for changes to Vue's code in v3, and created a static factory class:

```javascript
export default class CreateVueApplication
{
    static factory()
    {
        let app = Vue.createApp({ data() { return {} } });

        app.component('v-button', () => import(/* webpackChunkName:'js/button' */ '../vue/components/button.vue'));

        return app;
    }
}
```

Then, within my `app.js` file, I have the following:

```javascript
import CreateVueApplication from './factory.js';

let app = CreateVueApplication.factory().mount('#app');
```

The result is two separate errors:

1. Single file vue components are split, but they are massive (1 MB in size, where as they were previously ~18 KB).
2. The SFC scripts are not loaded (added as scripts to the page head) when Vue encounters the relevant components on the page.

In addition, the following message is printed as a warning in the console:

```
[Vue warn]: Invalid VNode type: – undefined – "(undefined)" (7)
"
"
" at <VButton"
"id=\"delete\""
">"
"
"
" at <App>"

**Comment by JeffreyWay** [comment] 2020-10-05 15:04
Have you gone through the update notes yet? Did you add `mix.vue()` to your `webpack.mix.js` file?

**Comment by mattkingshott** [comment] 2020-10-05 15:06
Yes, sorry, forgot to mention that I had added it and been explicit on the version number. 

My revised `webpack.mix.js` looks like this:

```javascript
mix.webpackConfig({
    resolve      : { symlinks: false },
    watchOptions : { ignored: /node_modules/ },
    output       : { publicPath: '/', chunkFilename: '[name].js?[hash]' },
});

mix.js('resources/js/app.js', 'public/js').vue({ version: 3 })
```

**Comment by mattkingshott** [comment] 2020-10-05 15:24
The console message in Chrome might provide some insight as it emitting the message "You are running a development build of Vue." This might indicate that Vue itself is being compiled into the component? Possibly accounting for the large file size?

**Comment by thecrypticace** [comment] 2020-10-05 15:49
Vue 3 async components require the use of `defineAsyncComponent `.
Try something like this:

```js
app.component('v-button', Vue.defineAsyncComponent(() => import(/* webpackChunkName:'js/button' */ '../vue/components/button.vue')));
```

**Comment by mattkingshott** [comment] 2020-10-05 15:56
Thanks for the suggestion @thecrypticace, unfortunately, it didn't fix the issue.

- The generated javascript files for each component are still 1MB +
- The scripts are still not being loaded in the head tag.
- The warning in the console is now slightly different: `[Vue warn]: Invalid VNode type: – Symbol(Comment) – "(symbol)"`

I also now receive the following error in the console:

```
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating '_ctx.window.document')
```

**Comment by mattkingshott** [comment] 2020-10-05 16:50
I've been able to partially fix the issue by removing the CDN link and changing my `app.js` like so:

```javascript
import { createApp, defineAsyncComponent } from 'vue';

app.component('v-button', defineAsyncComponent(() => import(/* webpackChunkName:'js/button' */ 	  '../vue/components/button.vue')));
```

Doing this removes all the errors and allows the components to load, however, I'd still like to be able to use the CDN.

I'm also able to confirm that `nom run production` causes the following error:

```
ChunkLoadError: Loading chunk 727 failed.
```

It also doesn't minify the individual component js files.

**Comment by thecrypticace** [comment] 2020-10-05 17:04
If you're using a CDN version of Vue the bundling won't work correctly. You'll have to treat vue as an external dependency using mix.autoload(…) but I've not tested that so I'm not sure what other gotchas there are. As for the chunk loading failure I'll take a look this evening and see what I can come up with.

In the mean time can you put up a sample repo with a reproduction of the problem?

**Comment by mattkingshott** [comment] 2020-10-05 17:43
That's interesting considering I never had an issue doing it with Vue v2 / Mix v5.

I've created a test repo here: https://github.com/mattkingshott/mix-vue-issue.

Thanks for all your help!

**Comment by craigrileyuk** [comment] 2020-10-06 08:45
> That's interesting considering I never had an issue doing it with Vue v2 / Mix v5.
Previously, Vue 2 imported the entire Vue bundle during the build process whereas in Vue 3, it will only import the methods and properties that you actually use.

**Comment by thecrypticace** [comment] 2020-10-06 12:35
Thanks for the test repo. That was helpful!

So it appears that manually setting the chunk filename `output: { chunkFilename: '[name].js?[hash]' },` causes the component loading failure. It looks like the chunk is generated with `/js/button` as the name but app.js loads `js/button`. That seems like it could be a webpack bug.

See: https://github.com/thecrypticace/mix-triage/blob/332605c928b832b99176e442a6101d6a3d4c3ce2/2516-vue-async-chunks/webpack.mix.js#L14

**Comment by mattkingshott** [comment] 2020-10-06 17:31
> Previously, Vue 2 imported the entire Vue bundle during the build process whereas in Vue 3, it will only import the methods and properties that you actually use.

Yeah, I'm just abandoning the CDN and importing / creating a `vendor.js` file

**Comment by mattkingshott** [comment] 2020-10-06 17:41
> Thanks for the test repo. That was helpful!
> 
> So it appears that manually setting the chunk filename `output: { chunkFilename: '[name].js?[hash]' },` causes the component loading failure. It looks like the chunk is generated with `/js/button` as the name but app.js loads `js/button`. That seems like it could be a webpack bug.
> 
> See: https://github.com/thecrypticace/mix-triage/blob/332605c928b832b99176e442a6101d6a3d4c3ce2/2516-vue-async-chunks/webpack.mix.js#L14

What's interesting is that I don't experience that on my main project. I have everything working other than running a production build...

**Comment by mattkingshott** [comment] 2020-10-07 07:09
For this following along, here is my current `webpack.mix.js` file:

```javascript
const mix = require('laravel-mix');
mix.webpackConfig(webpack => { return {
    resolve      : { symlinks: false },
    watchOptions : { ignored: /node_modules/ },
    output       : { publicPath: '/', chunkFilename: '[name].js?[hash]' },
    plugins      : [new webpack.DefinePlugin({ '__VUE_OPTIONS_API__': 'true', '__VUE_PROD_DEVTOOLS__': 'false' })],
}});

mix.extract()
   .js('resources/js/app.js', 'public/js').vue({ version: 3 });
```

**Comment by JeffreyWay** [comment] 2020-10-10 20:24
So is there a bug we need to address at this point, or am I free to close this issue?

**Comment by mattkingshott** [comment] 2020-10-10 20:28
Aside from the fact that you can’t do npm run production without getting the error I mentioned.

To be honest, I downgraded to Vue 2 / mix v5, so I’m not really able to confirm if the latest beta has fixed this.

On 10 Oct 2020, at 9:25 pm, Jeffrey Way <notifications@github.com<mailto:notifications@github.com>> wrote:


So is there a bug we need to address at this point, or am I free to close this issue?

**Comment by thecrypticace** [comment] 2020-10-12 22:41
Okay I've partially tracked this down. Webpack’s public path is set to `/` in the runtime and then it adds `/` to the beginning of the chunk filename resulting in //js/whatever.js as the public path is always prepended to chunk filenames. This is causing the loss of the host in the url when chunk loading. I'll see what I can figure out here.

**Closed** 2020-10-13 13:07 UTC
Labels: bug
