### ISSUE TITLE
npm run watch not working

### ISSUE THREAD

**Issue by Eldair** [JeffreyWay/laravel-mix#914] opened 2017-06-21 15:11 UTC
- Laravel Mix Version: 1.0.3
- Node Version (`node -v`): 8.1.2
- NPM Version (`npm -v`): 5.0.3
- OS:  win 10 Home v1703 build 15063.413

### Description:
Running `npm run watch` compiles everything but doesn't react on any changes made in main js file (first param of `.js()` method)

**Comment by JeffreyWay** [comment] 2017-06-21 21:20
Can you show me your webpack.mix.js file?

**Comment by lookitsatravis** [comment] 2017-06-22 04:06
Not OP, but I'm having the same trouble on macOS. Note that this is not for a Laravel app but rather for a Laravel package. Everything works, it just doesn't react to changed files. Here is my config.

```js
mix.autoload({
     jquery: ['$', 'window.jQuery', 'jQuery'],
     tether: ['Tether'],
  })
  .webpackConfig({
    resolve: {
      alias: {
        'jquery-ui/widget': 'blueimp-file-upload/js/vendor/jquery.ui.widget.js'
      }
    }
  })
  .js('resources/assets/src/js/app.js', 'resources/assets/build/js')
  .sass('resources/assets/src/styles/app.scss', 'resources/assets/build/css')
  .setPublicPath('resources/assets/build')
  .setResourceRoot('/vendor/test/')
  .version()
  .then(() => {
    let publishAssetsCommand = 'cd ../../../ && php artisan vendor:publish --provider="Test\\Package\\PackageServiceProvider" --tag=-public --force';
    exec(publishAssetsCommand, function (error, stdout, stderr) {
      if (error) {
        console.log("Package assets could not be published:", error);
      } else {
        console.log("Package assets published!");
      }
    });
  });
```

**Comment by eddiemf** [comment] 2017-06-22 04:37
Same problem here, it reacts to SCSS files only, but not for js.
Using MacOS and laravel-mix 1.0.3, following webpack.mix.js:

```
let mix = require('laravel-mix');
mix.js('src/js/app.js', 'dist/js');
``` 

As @lookitsatravis says, everything works (compiles after `npm run watch`) but won't compile after JS change.

**Comment by johanobergman** [comment] 2017-06-22 07:29
I'm having the same issue. It worked as intended with a small js file with some dependencies, but when I added some more (in my case it was 'react-router-dom'), it broke. Maybe it's an issue with webpack 3?

**Comment by Eldair** [comment] 2017-06-22 08:55
Here is my webpack.mix.js as well
```
let mix = require('laravel-mix');

mix.webpackConfig({
    module: {
        rules: [
            {
                test: /datatables\.net.*/,
                use: 'imports-loader?define=>false',
            }
        ],
    },
});

mix.sass('resources/assets/sass/app.scss', 'public/css/main.css')
    .js('resources/assets/js/app.js', 'public/js/main.js');

if (mix.inProduction()) {
    mix.version();
}
```

**Comment by LostKobrakai** [comment] 2017-06-22 13:50
Had the same issue and downgrading to webpack 2.6.1 resolved it.

**Comment by JeffreyWay** [comment] 2017-06-22 14:17
I *think* it's related to this webpack bug:

https://github.com/webpack/webpack/issues/5132

I've disabled scope hoisting in Mix until this is fixed. It's tagged as 1.0.5. 

Can one of you confirm that this issue is fixed after updating?

**Comment by LostKobrakai** [comment] 2017-06-22 14:21
It's detecting the .js changes again for me.

**Comment by eddiemf** [comment] 2017-06-22 14:23
Yeah, it's fixed :)

Thanks 👍

**Comment by JeffreyWay** [comment] 2017-06-22 14:31
Woohoo! Closing.

**Closed by JeffreyWay** 2017-06-22 14:31 UTC

**Comment by jbbr** [comment] 2017-06-22 15:12
Why not just enable scope hoisting in production only? It probably has an negative impact on rebuild performance and afaik does not provide any benefits during development.
This could also be handled like versioning and explicitly enabled with something like `.scopeHoisting()`.
