### ISSUE TITLE
Error on commands dev and production

### ISSUE THREAD

**Issue by rorc** [JeffreyWay/laravel-mix#274] opened 2017-02-02 20:05 UTC
Hello 😃

If i run commands by `npm run dev` or `npm run production`, then after some seconds i see this error in console:
```
ERROR  Failed to compile with 1 errors

 error

/js/app.js from UglifyJs
SyntaxError: Unexpected token: operator (>) [./~/bootstrap/js/src/util.js:8,0][/js/app.js:81,19]
```

**Comment by JeffreyWay** [comment] 2017-02-03 01:20
Can you check where that syntax error and paste the related code?

**Comment by rorc** [comment] 2017-02-03 07:34
Yea, this string is `const Util = (($) => {` (19 symbol from left)
https://github.com/twbs/bootstrap/blob/v4-dev/js/src/util.js

**Comment by rorc** [comment] 2017-02-03 07:38
That error shows if i use `npm run production`
But if i use `npm run dev`, then compiling is succesfully, but with error: http://joxi.ru/eAO4PzGtXB4nro

**Comment by JeffreyWay** [comment] 2017-02-03 21:41
I'm assuming it's related to Uglify trying to run on ES6 code. 

Can you give me basic steps to reproduce this error?

**Comment by rorc** [comment] 2017-02-04 08:46
Yea, i have three dependencies in `package.json`:
```javascript
"jquery": "^3.1.0",
"bootstrap": "^4.0.0-alpha.6",
"laravel-mix": "^0.5.0"
```

And my `app.js`:
```javascript
window.jQuery = window.$ = require('jquery');
require('bootstrap/js/src/util');
require('bootstrap/js/src/modal');
```

**Comment by CasperLaiTW** [comment] 2017-02-04 11:56
@rorc 
I think you have to require dist folder
```js
window.jQuery = window.$ = require('jquery');
require('bootstrap/js/dist/util');
require('bootstrap/js/dist/modal');
```

src files is ES6 code. and config exclude `node_modules` so webpack don't compile it.

**Comment by rorc** [comment] 2017-02-04 12:04
@CasperLaiTW I tryed, but without success =(
http://joxi.ru/52aQPgEfzM8x20

**Comment by CasperLaiTW** [comment] 2017-02-04 12:12
look not the same error.

can you provide more information for new error?

**Comment by rorc** [comment] 2017-02-04 12:22
Yea, ty)
That is content of `npm-debug.log` after running `npm run production`
http://pastebin.com/fy4Khfmg

**Comment by CasperLaiTW** [comment] 2017-02-04 12:27
@rorc Can you run this command

```shell
node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
```

and paste the log to check?

**Comment by rorc** [comment] 2017-02-04 12:29
@CasperLaiTW This finished without errors 😃
http://joxi.ru/4AkOKgaFqvN6Aq
Цhat's the problem?

**Comment by CasperLaiTW** [comment] 2017-02-04 12:49
Can you check your `package.json` scripts?
is it latest?
```json
{
  "scripts": {
      "dev": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "watch": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
      "hot": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
      "production": "node node_modules/cross-env/bin/cross-env.js NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
  },
}
```

**Comment by rorc** [comment] 2017-02-04 12:51
@CasperLaiTW Yes.

**Comment by CasperLaiTW** [comment] 2017-02-04 12:56
Do you check all the scripts were the same?

Because I wrote command just without '--hide-modules'

I think it no effect on run command

**Comment by rorc** [comment] 2017-02-04 12:59
@CasperLaiTW Yea, i copied and pasted each of your string of scripts and its same.

**Comment by CasperLaiTW** [comment] 2017-02-04 13:02
So you run `npm run production` will get errors
But use my script without '--hide-modules' will success and no errors?

**Comment by CasperLaiTW** [comment] 2017-02-04 13:06
Maybe you new issue relate #236

**Comment by rorc** [comment] 2017-02-04 13:38
@CasperLaiTW Yea, same problems, thanks 👍

**Comment by rorc** [comment] 2017-02-05 07:30
@CasperLaiTW By the way, with `require('bootstrap/js/dist/util');` and when i try to open bootstrap modal i got new error `ReferenceError: Util is not defined` 😕

**Comment by CasperLaiTW** [comment] 2017-02-05 09:52
@rorc Do you only use bootstrap modal?

I think you don't import Util. `bootstrap/js/dist/modal` was include `Util`

```js
window.jQuery = window.$ = require('jquery');
require('bootstrap/js/dist/modal');
```

**Comment by rorc** [comment] 2017-02-05 10:27
@CasperLaiTW Yes, at the moment from bootstrap i need only modal component.
No, `bootstrap/js/dist/modal` not including `Util.js`
Mayby problem with bootstrap plugin?

**Comment by CasperLaiTW** [comment] 2017-02-05 11:37
weird, I use bootstrap 4 and only import `bootstrap/js/dist/modal` and no errors.

do you use `bootstrap/js/dist/modal` and get errors?

**Comment by rorc** [comment] 2017-02-05 12:23
@CasperLaiTW Are you tried to open modal dialog?
If i just import `require('bootstrap/js/dist/modal');` i have no errors too 😄

**Comment by CasperLaiTW** [comment] 2017-02-05 12:27
@rorc 

Yes, I import `bootstrap/js/dist/modal` and open modal dialog.

modal shown and no errors

**Comment by JeffreyWay** [comment] 2017-02-08 17:57
Going to close this, since it seems the main issue was resolved.

**Closed by JeffreyWay** 2017-02-08 17:57 UTC

**Comment by nervo** [comment] 2017-03-28 13:35
@CasperLaiTW @rorc i'm just curious, if you use bootstrap in a modular approach (i mean `require('bootstrap/js/dist/modal')` instead of `require('bootstrap')`), using dist and not src, how do you declare your mix autoload ?

I've tried
```
    .autoload({
        ...
        'bootstrap/js/dist/tooltip': ['Tooltip']
    })
```

But browser console complains `Super expression must either be null or a function, not object`, wich means that "autoloaded" objects are not properly passed.

**Comment by opmind** [comment] 2017-06-18 22:44
I have solved same problem with import js files from src using #harmony version of ugifyjs:
package.json:
`"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"`
and resolve node_modules folder with bootstrap in babel-loader section of webpack.config.

**Comment by ghuachins** [comment] 2017-07-18 20:02
I'd been using that solution:
`"uglify-js": "git+https://github.com/mishoo/UglifyJS2.git#harmony"`
But, recently this not works for me because that link doesn't exists. is there another solution?
