### ISSUE TITLE
Cannot read property 'call' of undefined

### ISSUE THREAD

**Issue by tillkruss** [JeffreyWay/laravel-mix#582] opened 2017-03-17 03:36 UTC
- Laravel Mix Version: 0.8.8
- Node Version: v7.7.2
- NPM Version: 4.1.2 
- OS: macOs 10.12.3

### Description:

I'm getting the following errors:
```
Uncaught TypeError: Cannot read property 'call' of undefined (in manifest.js)
Uncaught TypeError: __WEBPACK_IMPORTED_MODULE_0_vue___default.a is not a constructor (in master.js)
```
<img width="478" alt="screen shot 2017-03-16 at 8 34 38 pm" src="https://cloud.githubusercontent.com/assets/665029/24027895/0acbe276-0a88-11e7-8313-d9bd50dca0eb.png">

Not sure if I'm doing something wrong. I laid out the setup the the comments below.

This occurs when using `npm run dev` and `npm run production`. I'm not using versioning, only extracting.

### Steps To Reproduce:

```js
import Vue from 'vue';

window.Vue = Vue;
window.bus = new Vue;
```

```js
mix.js('resources/assets/js/master.js', 'public/js')
   .extract(['vue'], 'public/js/vendor.js');
```

**Comment by tillkruss** [comment] 2017-03-17 03:37
The full setup looks like this:

```js
mix.js('resources/assets/js/master.js', 'public/js')
   .js('resources/assets/js/room.js', 'public/js')
   .js('resources/assets/js/listing.js', 'public/js')
   .js('resources/assets/js/account.js', 'public/js')
   .extract([
       'vue',
       'jquery',
       'js-cookie',
       'selectize',
       'pusher-js',
       'laravel-echo',
   ], 'public/js/vendor.js')
   .extract([
       'plupload',
       'sortablejs',
   ], 'public/js/vendor-account.js');
```

**Comment by tillkruss** [comment] 2017-03-17 03:39
The `master.js` file:

```js
require('./_bootstrap');

...
```

The `_bootstrap.js` file:

```js

/**
 * Import Vue module and create global event bus.
 */
import Vue from 'vue';

window.Vue = Vue;
window.bus = new Vue;
...
```

**Comment by wppd** [comment] 2017-03-17 05:27
I've encountered this same issue.

it's caused by webpack md5 hash https://github.com/erm0l0v/webpack-md5-hash/issues/9

**Comment by tillkruss** [comment] 2017-03-17 05:33
@wppd: Is there a fix for that, or does Mix need to be changed?

**Comment by wppd** [comment] 2017-03-17 06:35
@tillkruss 
I override Mix output method. it's where you define the file name pattern.

`'[name].[chunkhash].js'`

I simply replace chunkhash with timestamp. 

As you would expect, all files will be re-generated, even the vendors, when you run `npm run production`.  It's a lousy solution. 

I'm testing another solution now: HashedModuleIdsPlugin

you can copy webpack.config.js and replace `new webpackPlugins.WebpackMd5HashPlugin(),` with `new webpack.HashedModuleIdsPlugin`

**Comment by tillkruss** [comment] 2017-03-17 17:05
@wppd: I'm actually seeing this issue using `npm run dev`.

I tried replacing `plugins.WebpackMd5HashPlugin` with `webpack.HashedModuleIdsPlugin`, but that doesn't fix it for me.

Any other clues?

**Comment by tillkruss** [comment] 2017-03-17 17:13
Here is a screenshot of the full error:

<img width="668" alt="screen shot 2017-03-17 at 10 12 50 am" src="https://cloud.githubusercontent.com/assets/665029/24054701/58bde5de-0afa-11e7-8eac-ceb957e96eb0.png">

**Comment by JeffreyWay** [comment] 2017-03-17 17:22
Closing this, since it seems to be a duplicate of #581.

**Comment by tillkruss** [comment] 2017-03-17 17:24
@JeffreyWay: Is it? Using `HashedModuleIdsPlugin` doesn't fix it for me.

However I just found that setting `minChunks` to `1` solves it, not sure what the implications of that are.

**Comment by tillkruss** [comment] 2017-03-17 17:31
There seems to be a solution in https://github.com/webpack/webpack/issues/4445, but I have no idea how to put that into Mix, otherwise I'd make a PR.

**Comment by JeffreyWay** [comment] 2017-03-17 18:06
@tillkruss Does this still happen if you only call mix.extract() once?

**Comment by tillkruss** [comment] 2017-03-17 18:23
@JeffreyWay: No, it works fine with 2 `extract()` calls. 

I actually works fine with 3 as well, as long as the 3rd only contains a single vendor file?!

Works:

```js
.extract([
       'vue',
       'jquery',
       'js-cookie',
       'selectize',
       'pusher-js',
       'laravel-echo',
   ], 'public/js/vendor.js')
   .extract([
       'plupload',
       'sortablejs',
   ], 'public/js/vendor-account.js');
```

Works:

```js
.extract([
       'vue',
       'jquery',
       'js-cookie',
       'selectize',
       'pusher-js',
       'laravel-echo',
   ], 'public/js/vendor.js')
   .extract([
       'plupload',
       'sortablejs',
   ], 'public/js/vendor-account.js')
   .extract([
       'webrtc-adapter'
   ], 'public/js/vendor-room.js');
```

NOT Working:

```js
.extract([
       'vue',
       'jquery',
       'js-cookie',
       'selectize',
       'pusher-js',
       'laravel-echo',
   ], 'public/js/vendor.js')
   .extract([
       'plupload',
       'sortablejs',
   ], 'public/js/vendor-account.js')
   .extract([
       'video.js',
       'videojs-contrib-hls',
       'videojs-contrib-media-sources',
       'webrtc-adapter'
   ], 'public/js/vendor-room.js');
```

**Comment by tillkruss** [comment] 2017-03-17 18:36
Two is enough for me, three is just nice to have, not nessesary if it's to weird of an issue.

**Comment by ajcastro** [comment] 2017-05-24 13:18
I wonder if my problem is related to this, but when I use extract(), I got error on iCheck plugin. But If didnt use extract(), there is no error... I console.log the `$` variable in the plugin and it shows undefined when using extract().

**Closed** 2017-07-14 15:44 UTC

**Comment by manyeung** [comment] 2017-09-08 03:46
I encounter the same issue when I use `extract`. 

The problem occur when I am using `npm run hot` with `mix.extract()`. When I remove `mix.extract()`, everything goes well.

**Comment by MrSnoozles** [comment] 2017-09-15 16:09
@manyeung Same here. Getting the error with when running `npm run hot` with `mix.extract()`

**Comment by vedmant** [comment] 2018-09-08 09:53
I have the same problem when I run `yarn watch` but it works normally when I run `yarn prod`. I have .version() enabled. Does it means that I can't use `yarn watch` with enabled .version() ?

**Comment by njoguamos** [comment] 2019-04-17 22:44
I am having the same problem. I have dynamic imports enabled. When i run `yarn watch` everything works correctly. But when i run `yarn dev or yarn production` i get this error

> Here is a screenshot of the full error:
> 
> <img alt="screen shot 2017-03-17 at 10 12 50 am" width="668" src="https://cloud.githubusercontent.com/assets/665029/24054701/58bde5de-0afa-11e7-8eac-ceb957e96eb0.png">

**Comment by adriandmitroca** [comment] 2019-05-20 13:15
@njoguamos I am facing exactly the same issue, don't suppose you found a way over this?

**Comment by njoguamos** [comment] 2019-10-30 23:27
> @njoguamos I am facing exactly the same issue, don't suppose you found a way over this?

I ended up by disabling `.extract` 😐

**Comment by nmfzone** [comment] 2020-04-05 08:45
Here I faced this issue in Laravel Mix 5.0.4. Sadly, I'm not using `.extract()`, just install fresh Laravel 7.3, run `yarn run hot`, and this error happens.

@JeffreyWay

**Comment by gpressutto5** [comment] 2020-04-19 19:39
I'm not using `.extract()` and I'm getting the same error in a fresh new Laravel 7 project with `php artisan ui vue --auth`. Here's my webpack.mix.js file:

```js
const mix = require('laravel-mix');

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix.js('resources/js/app.js', 'public/js')
   .sass('resources/sass/app.scss', 'public/css');

```

**Comment by mdnurulmomen** [comment] 2020-05-03 16:50
I'm getting the same error without using .extract() method either.
Had a successfull build with _npm run dev_, but getting this error when browsing routes !!
Tried with _npm run production_ and _npm run watch_

**Comment by antonstsk** [comment] 2020-05-04 14:10
Same here, can't resolve this issue 😰

**Comment by adriandmitroca** [comment] 2020-05-04 21:39
If you are using dynamic imports (most likely you do when everything works in dev mode) you need to import blank .scss file at top of your app.js file.

This solves the issue.

**Comment by mdnurulmomen** [comment] 2020-05-07 09:55
@adriandmitroca 
Thanks Brother.
I've figured it out. You confirmed the issue.
Now, i'm fighting with another one.

// webpack.mix.js
`mix.webpackConfig(webpack => {
return {
output: {
publicPath: '/',
filename: '[name].js',
chunkFilename: 'js/[name].js',
},
};
});

mix.babelConfig({
plugins: ['@babel/plugin-syntax-dynamic-import'],
});

mix.js('resources/js/app.js', 'public/js')
.sass('resources/sass/app.scss', 'public/css');`


// app.js
const router = new VueRouter({ mode : 'history', routes : [ { path: '/home', name: 'admin.home', component: () => import(/* webpackChunkName : "home-component" */ './components/admin/HomeComponent.vue') }, { path: '/restaurants', name: 'admin.restaurants.index', component: () => import(/* webpackChunkName : "restaurant-list" */'./components/admin/RestaurantIndexComponent.vue') }, ], });

But Still npm run dev/watch emitting 0.js, 1.js, rather than home-component.js , restaurant-list.js.

Please Help me out.

**Comment by adriandmitroca** [comment] 2020-05-07 10:20
I'm not using named chunks. Why do you need them?

**Comment by mdnurulmomen** [comment] 2020-05-07 10:54
I'm using dynamic import for better user experience as i have more than 30 vue components so far.

**Comment by adriandmitroca** [comment] 2020-05-07 10:58
Sure, I get that. But that doesn't mean that you have to use named chunks. Default ones (0.js, 1.js, 2.js) are good enough for that.

**Comment by mdnurulmomen** [comment] 2020-05-07 11:02
I thought to get better readable chunks.

**Comment by adriandmitroca** [comment] 2020-05-07 11:09
To be honest it is totally redundant (happens only behind the scenes, only browser sees chunk names) but from your side requires extra comments in your code that looks messy.

I think it is worth reconsidering if its worth it.

**Comment by mdnurulmomen** [comment] 2020-05-07 11:17
Ow, Okay.
Except looking numbered name, its all working fine.

As i'm developing dynamic imports for the first time, i'm eager.
If chunk names are named manually, is it gonna seen only by browser ??
But, I've seen the named chunks at other places so far.

**Comment by adriandmitroca** [comment] 2020-05-07 11:38
Yeah, you don't really have to care about chunks names. It's unnecessary issue for you.

**Comment by nmfzone** [comment] 2020-05-07 11:39
@mdnurulmomen It seems your issue is different from the original issue. Please don't spam unrelated issue, since we all get notified. Thanks

**Comment by mdnurulmomen** [comment] 2020-05-07 16:59
Okay, My Apologies.
Anyway, Thanks @adriandmitroca .

**Comment by Helle1** [comment] 2021-01-15 10:25
> If you are using dynamic imports (most likely you do when everything works in dev mode) you need to import blank .scss file at top of your app.js file.
> 
> This solves the issue.

how would I achieve this? can you give me an example?

**Comment by adriandmitroca** [comment] 2021-01-15 10:44
Create empty scss file and then just import it (like JS file) inside your main JS file that's processed by Mix.

**Comment by bci24** [comment] 2022-09-16 10:43
Similar issue here.

When build for production .... i have to open dev tools and check "disable cache" ... then refresh to load the changes.

Laravel: 9.27
laravel-mix: 6.0.49
vue: 3.2.37

**webpack.mix.js**

```
mix.js('resources/js/app.js', 'public/js')
.extract()
.vue({ version: 3} )
.sass('resources/sass/app.scss', 'public/css')
.version();

mix.alias({
    '@main_app': path.join(__dirname, 'resources/js'),
})
```

and the resources are loaded in **app.blade.php**

```
<link href="{{ mix('/css/app.css') }}" rel="stylesheet">
<script src="{{ mix('/js/manifest.js') }}" defer></script>
<script src="{{ mix('/js/vendor.js') }}" defer></script>
<script src="{{ mix('/js/app.js') }}" defer></script>
```

Any idea how to solve this cache issue ?

**Comment by nmfzone** [comment] 2022-09-16 19:53
@bci24 Do you think your issue related to this thread? How?
