### ISSUE TITLE
feature request: add support for bundling .css files

### ISSUE THREAD

**Issue by iraklisg** [JeffreyWay/laravel-mix#243] opened 2017-01-31 09:44 UTC
When I try to import [element-ui](https://github.com/ElemeFE/element) css in my project, I run into the following error:
```
error  in ./~/element-ui/lib/theme-default/index.css

Module parse failed: /home/igeorgas/webApps/apptree2/node_modules/element-ui/lib/theme-default/index.css Unexpected character '@' (1:0)
You may need an appropriate loader to handle this file type.

| @charset "UTF-8";.el-breadcrumb:after,.el-breadcrumb:before,.el-form-item:after, ... /*more output*/ ...
```
My `main.js` entry point 

```
/**
 * Import project's dependencies
 */
import Vue from "vue";
import ElementUI from "element-ui";
import "element-ui/lib/theme-default/index.css"; // <--- this line causes the error

```

My `webpack.mix.js`
```
mix.js('resources/assets/js/main.js', 'public/js/app.js');
```

Now, In order to overcome this I had to manually configure and reference the built-in` webpack.config.js` by adding the following lines:

{
    test: /\.css$/,
    loader: 'style-loader!css-loader'
},

@JeffreyWay  Although its indeed very simple to modify the original `webpack.config.js` file, IMHO It could be helpful to add support for handling `.css` files in the next `laravel-mix` version, since handling `.css` files is a very common task .

Please also refer to [this](https://github.com/webpack-contrib/css-loader/issues/355) issue

**Comment by adriaanzon** [comment] 2017-01-31 13:04
Duplicate of https://github.com/JeffreyWay/laravel-mix/issues/190

**Closed** 2017-01-31 15:02 UTC
