### ISSUE TITLE
Possibly a Mix issue with webpack 5.25?

### ISSUE THREAD

**Issue by roddypratt** [JeffreyWay/laravel-mix#2887] opened 2021-03-12 17:28 UTC
-   Laravel Mix Version: #.#.# 6.0.13
-   Node Version 14.12.0
-   NPM Version 1.22.5
-   OS:Windows 

### Description: 
Just a heads-up that the latest Webpack build seems to have introduced behaviour that impacts some Mix users.  Unclear yet if it's a Mix problem or a Webpack one :(

https://github.com/webpack/webpack/issues/12880

Basically, Webpack loads your modules but doesn't run them...

### Steps To Reproduce:
It's complicated...

**Comment by obj63mc** [comment] 2021-03-12 19:35
I am getting the same issue, code will compile but when loaded in the browser the JS will not ever actually run.

**Comment by 6XGate** [comment] 2021-03-12 20:35
I can confirm this happens.  Not sure if it's Mix or Webpack.

**Comment by runyan-co** [comment] 2021-03-13 08:23
Can also confirm this is happening to me as well. It definitely started when I upgraded node to 15.11.0 and yarn to 1.22.10. Running on macOS Big Sur v11.2.3.

**Comment by schrink** [comment] 2021-03-13 10:20
+1

**Comment by roddypratt** [comment] 2021-03-13 11:26
To confirm if it's the same issue, look at the foot of the generated js files.  If you see something like..

`/******/ var __webpack_exports__ = __webpack_require__.O(undefined, ["css/mycssfile", /js/vendor"], ...`

...referencing css files, it's likely the same issue. You can try removing the "css/mycssfile" bits, and then the bundles should load an run correctly.

**Comment by risingphoenix** [comment] 2021-03-13 14:25
+1

**Comment by thecrypticace** [comment] 2021-03-13 14:52
Yeah this is a webpack bug downgrading Mix isn't going to help here. I recommend pinning webpack at 5.24.4 until this issue is fixed.

**Comment by runyan-co** [comment] 2021-03-13 23:58
> Yeah this is a webpack bug downgrading Mix isn't going to help here. I recommend pinning webpack at 5.24.4 until this issue is fixed.

Appreciate the advice! I've been researching exactly how to pin a dependency, but I seem to be creating more of a mess than helping get Mix working again. If you have a moment and ere able, would you mind sharing more specifics on how one would go about pinning the dependency and getting Mix to function temporarily while webpack is being patched? 🙂

**Comment by madpilot78** [comment] 2021-03-14 00:35
@runyan-co For yarn I added this:

```
    "resolutions": {
        "webpack": "=5.24.4"
    },
```

Looks like nom does not support this natively, this should help:

https://github.com/rogeriochaves/npm-force-resolutions

**Comment by thecrypticace** [comment] 2021-03-14 01:22
@runyan-co @madpilot78 

No need to use resolutions here. You can either edit your package.json to add `"webpack": "5.24.4"` to `devDependencies` or you can run the following:

Yarn: `yarn add webpack@5.24.4` (Note: I also had to add css-loader and postcss-loader after this — it shouldn't be necessary but seemingly is)

NPM: `npm install -E webpack@5.24.4`

**Comment by runyan-co** [comment] 2021-03-14 05:32
> @runyan-co @madpilot78 
> 
> 
> 
> No need to use resolutions here. You can either edit your package.json to add `"webpack": "5.24.4"` to `devDependencies` or you can run the following:
> 
> 
> 
> Yarn: `yarn add webpack@5.24.4` (Note: I also had to add css-loader and postcss-loader after this — it shouldn't be necessary but seemingly is)
> 
> 
> 
> NPM: `npm install -E webpack@5.24.4`
> 
> 

Thank you for the suggestion! I'll definitely start there and see if I can get it working. 👍🏻

**Comment by madpilot78** [comment] 2021-03-14 09:51
> @runyan-co @madpilot78
> 
> No need to use resolutions here. You can either edit your package.json to add `"webpack": "5.24.4"` to `devDependencies` or you can run the following:
> 

I don't want to avoid using resolutions, I like them, this is exactly what they are for and the meaning of the stanza is clear. Otherwise the "fix" gets lost in a bunch of other unrelated dependencies. Once the problem is fixed I simply remove the resolutions stanza.

Obviously everyone has his own preference.

**Comment by runyan-co** [comment] 2021-03-14 20:02
If it helps anyone, I did end up using @madpilot78 's method (thank you, by the way!) and it works well. I use yarn as my package manager, so I didn't have to use the npm-force-resolutions package as yarn natively supports the  resolutions option in package.json.

**Comment by sunscreem** [comment] 2021-03-14 20:09
I've pinned my webpack to to 5.24.4 but now the `extract()` mix helper only generates `app.js` and `mix-manifest.js` no `vendor.js`.

**Comment by madpilot78** [comment] 2021-03-14 20:20
Webpack issue  webpack/webpack#12880 has been fixed, they released version 5.25.1 with the fix, so I think the best solution now is to just upgrade.

**Comment by thecrypticace** [comment] 2021-03-14 20:32
Yep, upgrading is the best option now that the fix has been released.

Thanks again @roddypratt for letting us know about this one

**Closed by thecrypticace** 2021-03-14 20:32 UTC
