### ISSUE TITLE
gulp-util@3.0.8 is deprecated.

### ISSUE THREAD

**Issue by chriz74x** [JeffreyWay/laravel-mix#1401] opened 2018-01-09 16:48 UTC
- Laravel Mix Version: laravel-mix@1.7.2
- Node Version: 9.2.1
- NPM Version:  5.6.0
- OS: MacOS 10.13.2

### Description:

gulp-util@3.0.8 is deprecated. 
https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5.
installing a new laravel project and running npm install results in these warnings, not sure if the EINTEGRITY is related to gulp-util though. It seems a dependency of laravel-mix dependencies is using this (gulp-decompress).

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-aALmJk79GMeQobDVF/DyYnvyyUo= integrity checksum failed when using sha1: wanted sha1-aALmJk79GMeQobDVF/DyYnvyyUo= but got sha512-Y9J6ZjXtoYh8RnXVCMOU/ttDmk1aBjunq9vO0ta5x85WDQiQfUF9sIPBITdbiiIVcBo03Hi3jMxigBtsddlXRw==. (3526 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-+PLIh60Qv2f2NPAFtph/7TF5qsg= integrity checksum failed when using sha1: wanted sha1-+PLIh60Qv2f2NPAFtph/7TF5qsg= but got sha512-nne9/IiQ/hzIhY6pdDnbBtz7DjPTKrY00P/zvPSm5pOFkl6xuGrGnXn/VtTNNfNtAfZ9/1RtehkszU9qcTii0Q==. (2301 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-qRlH2h9KUW6jjltOwOw3c2deCIY= integrity checksum failed when using sha1: wanted sha1-qRlH2h9KUW6jjltOwOw3c2deCIY= but got sha512-dwVUVIXsBZXwTuwnXI9RK8sBmgq09NDHzyR9SAph9eqk76gKK2JSQmZARC2zRC81JC2QTtxD0ARU5qTS25gIGw==. (4568 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.
WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EINTEGRITY: sha1-QKBQ7I3DtTsz2ZCUFcAsC/Gr+60= integrity checksum failed when using sha1: wanted sha1-QKBQ7I3DtTsz2ZCUFcAsC/Gr+60= but got sha512-c0yTD2rbQzXtSsFSVhtpvY/vS6u066PcXOX9kBB3mSO76RiUQzL340uJkGBWnlBg4/HZzqiUXtaVA7wcRcJgEw==. (49753 bytes)
WARN registry Using stale package data from https://registry.npmjs.org/ due to a request error during revalidation.

```

### Steps To Reproduce:

install a new laravel project and run npm install

**Comment by ankurk91** [comment] 2018-01-10 13:27
Duplicate of
https://github.com/JeffreyWay/laravel-mix/issues/1395

**Closed** 2018-01-16 18:27 UTC

**Comment by billdanbury** [comment] 2018-03-15 18:42
Problem persists as of laravel-mix 2.1.1 via gulp-decompress@1.2.0. Please reopen this issue for resolution.

```
└─┬ laravel-mix@2.1.1
  └─┬ img-loader@2.0.1
    └─┬ imagemin-gifsicle@5.2.0
      └─┬ gifsicle@3.0.4
        └─┬ bin-build@2.2.0
          └─┬ download@4.4.3
            └─┬ gulp-decompress@1.2.0
              └── gulp-util@3.0.8
```

**Comment by t202wes** [comment] 2018-04-04 20:40
Having an issue as well

```
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

npm WARN prefer global node-gyp@3.6.2 should be installed with -g
```

**Comment by mojtabaavdev** [comment] 2018-06-09 11:54
I'm also having this issue. npm install stops working after this warning is shown.

**Comment by D4ITON** [comment] 2018-06-11 04:48
I only install gulp, gulp-sass, and create an gulpfile.js into the proyect, then use the directives. see this video, it help me: https://www.youtube.com/watch?v=e1G7ZpwoRe4

**Comment by SodomousPrime** [comment] 2018-06-12 02:44
From fresh install of Laravel Framework 5.6.24. With no changes made. fails at "npm install",
![npm-message-info](https://user-images.githubusercontent.com/15336394/41267128-821ec6bc-6e3d-11e8-848d-e4b96de78c56.png)
