### ISSUE TITLE
using yarn as replacement does not work

### ISSUE THREAD

**Issue by morloderex** [JeffreyWay/laravel-mix#82] opened 2017-01-11 21:38 UTC
Hello, today i decided to try out this package. 
I went ahead and installed the package but **NOT** through npm instead i tried to install it with yarn. 

But when i run any of the npm scripts described in the documentation compilation fails with a message saying something like `cross-env is not found`.

I know this is specific to a yarn installation because with a traditional `npm install` it works without any issue. 

Anyone who can say anything about way this is the case?

**Comment by JeffreyWay** [comment] 2017-01-11 21:51
There's a GitHub issue for the Yarn repo to get that fixed. So closing for now.

**Closed by JeffreyWay** 2017-01-11 21:51 UTC

**Comment by Evertt** [comment] 2017-01-14 18:18
@JeffreyWay, can you maybe point me to the issue you're talking about? I can't find it on the yarn repo.

**Comment by mathieutu** [comment] 2017-01-19 15:22
@Evertt I've posted a comment on theses two issues for yarn which seem to be our problem: 
- https://github.com/yarnpkg/yarn/issues/733
- https://github.com/yarnpkg/yarn/issues/735

They are supposed to be closed, but obviously not, looking at our case.

**Comment by adriaanzon** [comment] 2017-01-19 16:37
I think the problem is that the binaries of recursive dependencies don't end up in `node_modules/.bin`, like this issue: https://github.com/yarnpkg/yarn/issues/2493

Only when you explicitly add them to your project (`yarn add --dev cross-env webpack`) the binaries will end up in there.

**Comment by mathieutu** [comment] 2017-01-19 16:40
Yeah but this is just a (brand new) duplicate of the ones I've gave.
