### ISSUE TITLE
Invalid options object. Mini CSS Extract Plugin

### ISSUE THREAD

**Issue by it-can** [JeffreyWay/laravel-mix#2603] opened 2020-11-06 14:51 UTC
-   Laravel Mix Version: 6.0.0-beta.13 (`npm list --depth=0`)
```
├── @fortawesome/fontawesome-free@5.15.1
├── bootstrap@3.4.1
├── cross-env@7.0.2
├── jquery@3.5.1
├── laravel-mix@6.0.0-beta.13
├── lazysizes@5.2.2
├── less-loader@7.0.2
├── less@3.12.2
└── postcss@8.1.6
```

-   Node Version (`node -v`): v15.1.0
-   NPM Version (`npm -v`): 7.0.8
-   OS: Mac OS X Big Sur latest beta

### Description:
When running ```npm run prod``` I get this error

```
> prod
> npm run production


> production
> mix --production

[webpack-cli] ValidationError: Invalid options object. Mini CSS Extract Plugin has been initialized using an options object that does not match the API schema.
 - options has an unknown property 'esModule'. These properties are valid:
   object { filename?, chunkFilename?, ignoreOrder?, insert?, attributes?, linkType? }
    at validate (/Users/test/websites/laravel/test/node_modules/mini-css-extract-plugin/node_modules/schema-utils/dist/validate.js:104:11)
    at new MiniCssExtractPlugin (/Users/test/websites/laravel/test/node_modules/mini-css-extract-plugin/dist/index.js:47:31)
    at CssWebpackConfig.webpackPlugins (/Users/test/websites/laravel/test/node_modules/laravel-mix/src/components/CssWebpackConfig.js:145:13)
    at ComponentRegistrar.applyPlugins (/Users/test/websites/laravel/test/node_modules/laravel-mix/src/components/ComponentRegistrar.js:186:23)
    at /Users/test/websites/laravel/test/node_modules/laravel-mix/src/components/ComponentRegistrar.js:86:50
    at /Users/test/websites/laravel/test/node_modules/laravel-mix/src/Dispatcher.js:34:69
    at Array.map (<anonymous>)
    at Dispatcher.fire (/Users/test/websites/laravel/test/node_modules/laravel-mix/src/Dispatcher.js:34:54)
    at Mix.dispatch (/Users/test/websites/laravel/test/node_modules/laravel-mix/src/Mix.js:108:32)
    at WebpackConfig.buildPlugins (/Users/test/websites/laravel/test/node_modules/laravel-mix/src/builder/WebpackConfig.js:125:13) {
  errors: [
    {
      keyword: 'additionalProperties',
      dataPath: '',
      schemaPath: '#/additionalProperties',
      params: [Object],
      message: 'should NOT have additional properties',
      schema: false,
      parentSchema: [Object],
      data: [Object]
    }
  ],
  schema: {
    type: 'object',
    additionalProperties: false,
    properties: {
      filename: [Object],
      chunkFilename: [Object],
      ignoreOrder: [Object],
      insert: [Object],
      attributes: [Object],
      linkType: [Object]
    }
  },
  headerName: 'Mini CSS Extract Plugin',
  baseDataPath: 'options',
  postFormatter: null
}
npm ERR! code 2
npm ERR! path /Users/test/websites/laravel/test
npm ERR! command failed
npm ERR! command sh -c webpack --progress '--config=/Users/test/websites/laravel/test/node_modules/laravel-mix/setup/webpack.config.js'

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/test/.npm/_logs/2020-11-06T14_47_45_733Z-debug.log
```

Log file:

```
0 verbose cli [
0 verbose cli   '/usr/local/Cellar/node/15.1.0/bin/node',
0 verbose cli   '/usr/local/lib/node_modules/npm/bin/npm-cli.js',
0 verbose cli   'exec',
0 verbose cli   '--',
0 verbose cli   'webpack',
0 verbose cli   '--progress',
0 verbose cli   '--config=/Users/test/websites/laravel/test/node_modules/laravel-mix/setup/webpack.config.js'
0 verbose cli ]
1 info using npm@7.0.8
2 info using node@v15.1.0
3 timing config:load:defaults Completed in 1ms
4 timing config:load:file:/usr/local/lib/node_modules/npm/npmrc Completed in 1ms
5 timing config:load:builtin Completed in 1ms
6 timing config:load:cli Completed in 1ms
7 timing config:load:env Completed in 0ms
8 timing config:load:file:/Users/test/websites/laravel/test/.npmrc Completed in 0ms
9 timing config:load:project Completed in 1ms
10 timing config:load:file:/Users/test/.npmrc Completed in 0ms
11 timing config:load:user Completed in 0ms
12 timing config:load:file:/usr/local/etc/npmrc Completed in 0ms
13 timing config:load:global Completed in 0ms
14 timing config:load:cafile Completed in 0ms
15 timing config:load:validate Completed in 1ms
16 timing config:load:setUserAgent Completed in 0ms
17 timing config:load:setEnvs Completed in 0ms
18 timing config:load Completed in 5ms
19 verbose npm-session 8bae3729dc521a2f
20 timing npm:load Completed in 10ms
21 timing command:exec Completed in 1217ms
22 verbose stack Error: command failed
22 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/@npmcli/promise-spawn/index.js:64:27)
22 verbose stack     at ChildProcess.emit (node:events:327:20)
22 verbose stack     at maybeClose (node:internal/child_process:1055:16)
22 verbose stack     at Process.ChildProcess._handle.onexit (node:internal/child_process:288:5)
23 verbose cwd /Users/test/websites/laravel/test
24 verbose Darwin 20.1.0
25 verbose argv "/usr/local/Cellar/node/15.1.0/bin/node" "/usr/local/lib/node_modules/npm/bin/npm-cli.js" "exec" "--" "webpack" "--progress" "--config=/Users/test/websites/laravel/test/node_modules/laravel-mix/setup/webpack.config.js"
26 verbose node v15.1.0
27 verbose npm  v7.0.8
28 error code 2
29 error path /Users/test/websites/laravel/test
30 error command failed
31 error command sh -c webpack --progress '--config=/Users/test/websites/laravel/test/node_modules/laravel-mix/setup/webpack.config.js'
32 verbose exit 2

```

**Comment by arcanedev-maroc** [comment] 2020-11-06 14:53
I'm having the same issue right now (Windows 8.1)

**Comment by JeffreyWay** [comment] 2020-11-06 14:56
I'm seeing this, too, all of the sudden. There might have been a breaking change in one of our dependencies. I'm looking into it now.

**Comment by arcanedev-maroc** [comment] 2020-11-06 14:56
I think this is caused by this release: https://github.com/webpack-contrib/mini-css-extract-plugin/releases/tag/v1.3.0

**Comment by JeffreyWay** [comment] 2020-11-06 14:57
^ Yep, that's it.

**Comment by JeffreyWay** [comment] 2020-11-06 15:03
Okay, this is fixed in beta.14.

**Closed** 2020-11-06 15:02 UTC

**Comment by TatyanaMolchanova** [comment] 2021-07-25 07:54
Problem is in .browserslist 
Add to webpack.config.js

target: process.env.NODE_ENV === "development" ? "web" : "browserslist",
