### ISSUE TITLE
Enable version hash of 0.12.x

### ISSUE THREAD

**Issue by tpetry** [JeffreyWay/laravel-mix#1085] opened 2017-08-01 08:09 UTC
- Laravel Mix Version: 1.4.2

### Description:
Laravel Mix 0.12.x and before had the nice file hash of `path/filename.hash.extension`. This was really helpful if you used a CDN because you could dump the assets of every version to the CDN and could run several different versions of your sourcecode with different assets on every server. Now with v1 the file hash changed to the query parameter (`path/filename.extension?id=hash`) which removes this feature. Additional rollouts are complicated because asset and mix-manifest.json have to be exactly the same on every server on the same time  or you will have race-conditions requesting the wrong asset for a hashing id which will have catastrophic effects if you use browser caching.

It should be possible to activate the old filename hashing instead of the new query hashing if requested.

### Steps To Reproduce:
It seems not to be possible to do this by our own because webpack-config will only apply the filename parameter to the first occurence of an asset, in this case `.js` and not `.css`:
```js
const { mix } = require('laravel-mix');

// chunkFilename: '[name]-[chunkhash].js'
mix.options()
    .webpackConfig({
        output: {
            filename: "[name].[hash].someextension" // there's no param for dynamic extensions
        }
    })
   .js('resources/assets/js/app.js', 'public/js')
   .sass('resources/assets/sass/app.scss', 'public/css')
   .version()
```

```
$ cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js 
 95% emitting                                                                           

 DONE  Compiled successfully in 22607ms                                                                                                                                                                                     8:04:46 AM

                                     Asset     Size  Chunks                    Chunk Names
/js/app.bcf1d095bb59335ba5bd.someextension  3.72 MB       0  [emitted]  [big]  /js/app
                              /css/app.css   300 kB       0  [emitted]  [big]  /js/app
Done in 32.56s.
```

**Comment by JeffreyWay** [comment] 2017-08-01 15:02
Duplicate of #1022

**Closed by JeffreyWay** 2017-08-01 15:02 UTC
