### ISSUE TITLE
Javascript File Deleted After SCSS Change

### ISSUE THREAD

**Issue by kevin-coyle** [JeffreyWay/laravel-mix#844] opened 2017-05-31 15:16 UTC
- Laravel Mix Version: 0.12.1
- Node Version: 6.9.5  
- NPM Version: 3.10.10 
- OS: OS X 10.12

### Description:

After initial compilation when changing a SCSS file in a build that contains only scss and js then when the scss is changed the JS is deleted.

### Steps To Reproduce:

On OSX follow these instructions:

```
#Create a temp project
mkdir /tmp/jsbug
cd /tmp/jsbug
#Create a default package.json
npm init -y
npm install lavavel-mix --save-dev
cp -r node_modules/laravel-mix/setup/** ./
touch style.scss
touch app.js
```
Copy in the lines to the package.json like in the documentation
```
  "scripts": {
    "dev": "cross-env NODE_ENV=development webpack --progress --hide-modules",
    "watch": "cross-env NODE_ENV=development webpack --watch --progress --hide-modules",
    "hot": "cross-env NODE_ENV=development webpack-dev-server --inline --hot",
    "production": "cross-env NODE_ENV=production webpack --progress --hide-modules"
  }
```

Edit the webpack.mix.js file to contain for the jobs:

```
let mix = require('laravel-mix');
mix.js('app.js', 'dist/')
.sass('style.scss', 'dist/');
```

Now run `npm run watch`

Initially this will create the javascript file. Then edit the sass file. The javascript file is then deleted.

In addition an example github repo is here:

https://github.com/kevin-coyle/laravel-mix-bug

Thanks for any help that you can give.

**Comment by codefuhrer** [comment] 2017-06-01 01:45
I have the exact same problem with 0.12.1

**Comment by njbarrett** [comment] 2017-06-01 06:37
I've got this problem as well.

**Comment by ankurk91** [comment] 2017-06-01 09:19
Unfortunately I could not reproduce this issue.
Laravel mix : 0.12.1
npm: 3.10
node: 6.10
OS: Ubuntu x64

Here is my webpack.mix.js code -
```js
'use strict';
const mix = require('laravel-mix');
const buildDir = 'public/';

mix.js('./resources/assets/js/app.js', buildDir + 'js/app.js')
  .extract([
    'jquery',
    'querystring',
    'lodash',
    'axios',
    'messg',
    'vue-router',
    'vue-nprogress',
    'vue-infinite-loading',
    'vue-select',
    'flatpickr',
    'vue',
    'moment',
    'fullcalendar',
    'bootstrap'
  ])
  .autoload({
    jquery: ['$', 'window.jQuery', 'jQuery'],
    vue: ['window.Vue', 'Vue'],
    axios: ['window.axios', 'axios'],
    moment: ['window.moment', 'moment'],
    messg: ['window.messg', 'messg'],
  })
  .styles(['./resources/assets/css/app.css'], buildDir + 'css/app.css')
  .sass('./resources/assets/css/vendor.scss', buildDir + 'css/vendor.css')
  .version()
  .sourceMaps(false);
```

**Comment by Sunappnio** [comment] 2017-06-01 09:42
I have the same problem.
When I run "npm run watch", everything works fine
However when I change scss file, only css compiles, 
and the js file results on a 404 status

**Comment by huubk** [comment] 2017-06-01 11:44
I've got the same issue with 0.12.1

**Comment by xenonthong** [comment] 2017-06-05 08:16
Same issue here as well.

**Comment by EssamWD** [comment] 2017-06-05 13:54
I've the same issue

**Comment by filljoyner** [comment] 2017-06-06 05:17
Same issue here using Laravel Mix as a stand-alone.
npm run watch will compile css and js perfectly on startup. Then any updates to scss will remove the compiled js file and only recompile the scss file.

**Comment by jackmcdade** [comment] 2017-06-06 14:14
Having this when using as stand-alone as well.

**Comment by jackmcdade** [comment] 2017-06-06 14:25
As in #843, rolling back to `0.11.4` gets this working again for now.

**Comment by filljoyner** [comment] 2017-06-06 15:31
Running 0.11.4 produces same issue for me. :(

**Comment by JeffreyWay** [comment] 2017-06-06 15:35
I'm thinking this is already fixed in the 1.0 beta release. But just to be sure...

Is this happening within your Laravel projects? Or is it always in standalone projects that this occurs?

**Comment by jackmcdade** [comment] 2017-06-06 15:36
I haven't tried it in a Laravel project yet, just doing some front-end dev outside before i bring it into a legacy app.

**Comment by filljoyner** [comment] 2017-06-06 15:36
Same.

**Comment by JeffreyWay** [comment] 2017-06-06 15:38
Ah okay, good to know thanks. 

Mix 1.0 should automatically fix this. I'll be tagging it later this week.

**Comment by huubk** [comment] 2017-06-06 15:38
Haven't tried this in Laravel yet only standalone..

**Closed by JeffreyWay** 2017-06-06 15:38 UTC

**Comment by filljoyner** [comment] 2017-06-06 15:43
Did a quick test with clean install of Laravel. Working fine there.

**Comment by EssamWD** [comment] 2017-06-21 17:35
I did update to laravel mix 1.0.3 but I'm still have the same issue

**Comment by JeffreyWay** [comment] 2017-06-21 18:01
@EssamWD I doubt it. We don't delete any files in the 1.0 version. Can you run `npm list --depth=0` and make sure that it says 1.0.3 for laravel-mix?

**Comment by EssamWD** [comment] 2017-06-21 18:24
I removed the package and install it again and now everything work very well.. Thank you very much
