### ISSUE TITLE
Vue fails to run as expected with extract()

### ISSUE THREAD

**Issue by sfsaccone** [JeffreyWay/laravel-mix#2794] opened 2021-01-23 16:29 UTC
-   Laravel Framework Version: 8.24.0
-   Laravel Mix Version: 6.0.10
-   Node Version: 14.5.0
-   Vue Version: 3.0.5
-   NPM Version: 6.14.9
-   OS: Ubuntu Server 20.04 LTS

### Description:

When used with `.extract(['vue'])`, the browser (Edge) console shows a warning `runtime compilation is not supported in this build of Vue` and  instead of the data that's supposed to be displayed in a component it has `<!---->`.

Everything works as expected with this `webpack.mix.js` (I'm using Breeze):

```javascript
mix.js('resources/js/app.js', 'public/js')
    .vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);
```

But when I switched to the `extract` method it fails as described below. It
builds, but the code fails to run as expected.

```javascript
mix.js('resources/js/app.js', 'public/js')
    .extract(['vue'])
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);
```

It fails the same way if we remove both `vue()` and `extract()`. Note that while
the documentation seems to imply that `vue()` is required for single-file
component compilation support, I'm not using the single-file approach in this example.

```javascript
mix.js('resources/js/app.js', 'public/js').postCss(
    'resources/css/app.css',
    'public/css',
    [require('postcss-import'), require('tailwindcss'), require('autoprefixer')]
);
```

The Blade template:

```php
<div id="hello-vue">
    @{{ message }}
</div>
```

The JavaScript in `resources/js/app.js`:

```javascript
const HelloVueApp = {
    data() {
        return {
            message: 'Hello Vue!!',
        };
    },
};

window.addEventListener('DOMContentLoaded', (event) => {
    console.log('Binding Vue');
    Vue.createApp(HelloVueApp).mount('#hello-vue');
});
```

Browser (Edge) console messages:

```text
Binding Vue

[Vue warn]: Component provided template option but runtime compilation
is not supported in this build of Vue. Configure your bundler to alias
"vue" to "vue/dist/vue.esm-bundler.js".
```

Here's the resulting html from the dev tools. Instead of `Hello Vue!` we get
`<!---->`.

```html
<div id="hello-vue" data-v-app="">
    <!---->
</div>
```

The data is shown as expected without the extraction:

```javascript
mix.js('resources/js/app.js', 'public/js')
    .vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);
```

**Workaround**

If I use both the `extract()` and `vue()` methods in `webpack.mix.js` then it works as expected. I don't know why. I did not find documentation that described using both methods this way. However, this approach does appear in issue [2777](https://github.com/JeffreyWay/laravel-mix/issues/2777), but only with options like `.vue({version: 3, runtimeOnly: true})`. I tried using `.vue({version: 2})` in the file below but that results in a different error, so it doesn't seem to be that calling `vue()` is necessary to set the version to 3. With `.vue({version: 3})` it works as expected, the result is the same as `.vue()`. Note that the order in which `extract()` and `vue()` are called doesn't seem to matter. 

```javascript
mix.js('resources/js/app.js', 'public/js')
    .extract(['vue'])
    .vue()
    .postCss('resources/css/app.css', 'public/css', [
        require('postcss-import'),
        require('tailwindcss'),
        require('autoprefixer'),
    ]);
```

Is this the way `webpack.mix.js` is supposed to be configured? If not and if necessary I can post more detailed steps to reproduce starting with a new app.

**Comment by thecrypticace** [comment] 2021-01-23 18:12
Your file at the bottom where you're calling `mix.extract()` AND `mix.vue()` is what you should be using so I'm not sure what you are saying the problem is here.  If this answers your question feel free to close the issue.

Some notes:
1. Yes, a call to `mix.vue()` is indeed required for SFC support. This was implicit in Mix v5 but was turned into a feature flag in v6 that you must explicitly enable. In addition `mix.vue()` will configure webpack and Vue to use the appropriate files for bundling.
2. `mix.extract` pulls dependencies into a separate file. `mix.extract(['vue'])` will bundle Vue if and only if you include it in your app.js file (or an import somewhere down the line). Its use is orthogonal/unrelated to `mix.vue()` as they do two entirely different things.

**Comment by sfsaccone** [comment] 2021-01-23 19:41
Great, then I should be all set. 

Before I close this, note that the following example from the Mix [Vendor Extraction](https://laravel.com/docs/8.x/mix#vendor-extraction) section in the Laravel 8 documentation lacks the `.vue()` method (maybe it was intended to be implied?):

```javascript
mix.js('resources/js/app.js', 'public/js')
    .extract(['vue'])
```

Therefore, if I follow this example as is then I get the issue above. Either I'm still missing something, or the documentation needs to be updated. It sounds like I'm fine if I just follow your instruction above, so please feel free to close this.

Thanks!

**Comment by thecrypticace** [comment] 2021-01-24 00:59
The documentation itself doesn't necessarily need to be updated for that one example but it still should be. I'll make a note to go through it at some point when I get some time in the next few weeks. The reason you get the error about template compilation is that in Vue 3 the "default" import is the runtime build. When you use `mix.vue()` we change it back to the compiler-including build because that's the most commonly used variant with Laravel / Laravel Mix.

**Closed by thecrypticace** 2021-01-24 00:59 UTC
