### ISSUE TITLE
Multiple vendors

### ISSUE THREAD

**Issue by pderiy** [JeffreyWay/laravel-mix#161] opened 2017-01-25 15:18 UTC
Hi, Jeffrey,

I'm trying to run this code: 
```
mix
    .js('angular/b2b/index.main.ts', 'public/js/app.b2b.js')
    .extract([
        'angular'
    ]);

mix
    .js('angular/b2c/index.main.ts', 'public/js/app.b2c.js')
    .extract([
        'angular',
        'jquery'
    ]);
```
I have b2c & b2b modules. These 2 modules are using different packages. So I need **2 vendors**, maby something like:
```
vendor.b2b.js
vendor.b2c.js
```

Now it generates only 1 vendor:
```
                                                                    Asset       Size  Chunks                    Chunk Names
                                                     public/js/app.b2b.js    2.12 kB    0, 3  [emitted]         app.b2b
  fonts/glyphicons-halflings-regular.eot?f4769f9bdb7466be65088239c12046d1    20.1 kB          [emitted]         
  fonts/glyphicons-halflings-regular.ttf?e18bbf611f2a2e43afc071aa2f4e1512    45.4 kB          [emitted]         
 fonts/glyphicons-halflings-regular.woff?fa2772327f55d8198301fdb8bcfc8158    23.4 kB          [emitted]         
fonts/glyphicons-halflings-regular.woff2?448c34a56d699c29117adc64c43affeb      18 kB          [emitted]         
  fonts/glyphicons-halflings-regular.svg?89889688147bd7575d6327160d64e760     109 kB          [emitted]         
                                                      public/js/vendor.js     1.5 MB    1, 3  [emitted]  [big]  vendor
                                                     public/js/app.b2c.js  300 bytes    2, 3  [emitted]         app.b2c
                                                    public/js/manifest.js    5.56 kB       3  [emitted]         manifest
                                                       public/css/app.css     143 kB    0, 3  [emitted]         app.b2b
                                                        mix-manifest.json  248 bytes          [emitted]         

```

**Comment by JeffreyWay** [comment] 2017-01-25 18:17
Yeah you can only extract one set of vendor packages right now.

**Comment by JeffreyWay** [comment] 2017-01-25 18:18
Closing this, as it's a duplicate of #143.

**Closed by JeffreyWay** 2017-01-25 18:18 UTC
