### ISSUE TITLE
Uncaught TypeError: utils.isStandardBrowserEnv is not a function 

### ISSUE THREAD

**Issue by davidhoeck** [JeffreyWay/laravel-mix#1092] opened 2017-08-02 14:08 UTC
Just running "npm run watch" and I'm getting the error every 4-5 re-compilations. 

```
Uncaught TypeError: utils.isStandardBrowserEnv is not a function
    at Object.chars (app.js:64325)
    at __webpack_require__ (app.js:20)
    at Object.<anonymous> (app.js:26040)
    at __webpack_require__ (app.js:20)
    at getDefaultAdapter (app.js:10529)
    at Object.<anonymous> (app.js:10538)
    at Object.<anonymous> (app.js:10603)
    at __webpack_require__ (app.js:20)
    at Object.module.exports (app.js:63840)
    at __webpack_require__ (app.js:20)
```
__Everything is at the newest version__

**Comment by JeffreyWay** [comment] 2017-08-02 15:01
What does your webpack.mix.js file look like?

**Comment by davidhoeck** [comment] 2017-08-03 12:02
@JeffreyWay  

```
// app sass files
mix.sass('resources/assets/sass/framework.scss', 'public/css');
mix.sass('resources/assets/sass/app.scss', 'public/css');

// app js files
mix.js('resources/assets/js/app.js', 'public/js');

// copy font files
mix.copy('resources/assets/fonts', 'public/fonts');

// copy image files
mix.copy('resources/assets/images', 'public/images');


mix.browserSync({
    proxy: 'dev.beer-tasting.shop'
});
```

**Comment by webmarkelov** [comment] 2017-08-03 15:25
@davidhoeck Provide more information ([template](https://github.com/JeffreyWay/laravel-mix/blob/master/.github/ISSUE_TEMPLATE.mdl))

**Comment by bryandease** [comment] 2017-08-04 19:13
I'm getting the same error @davidhoeck - just started recently.  Seems to be working fine with watching JS files - but any updates I make to less files require me to stop and run a fresh watch.

**Comment by Balatsky** [comment] 2017-08-05 11:12
Got the same error after any update in sass files.

**Comment by chagoy** [comment] 2017-08-05 17:49
I've gotten this too. It started when I commented out everything in my app.scss files and used a CSS CDN. If I restore everything (uncomment the sass file, take out the CDN) I still get 'Uncaught TypeError: utils.isStandardBrowserEnv is not a function'.

**Comment by stebrl** [comment] 2017-08-07 09:57
Getting the same error every time I update my sass file...

**Comment by davidhoeck** [comment] 2017-08-07 10:09
@JeffreyWay I think it is coming from the axios library...

**Comment by franc014** [comment] 2017-08-07 16:56
Here the same problem when running **npm run watch**
I had to stop and run again to make it work when making any sass change.

**Comment by graddd** [comment] 2017-08-07 17:39
+ 1

**Comment by JhumanJ** [comment] 2017-08-09 13:04
Same here...

**Comment by jeffturcotte** [comment] 2017-08-09 13:52
@davidhoeck is right that this has something to do the axios library and it's utils file, but I'm guessing the bug is still somewhere within mix's own `watch` config.

**Here is a temporary fix**: require/import the full axios dist file. All of it's own internal dependencies will be included and webpack/mix won't need to load them. The following works for me and solves this very annoying issue.

`window.axios = require('axios/dist/axios.js');`

**Comment by JeffreyWay** [comment] 2017-08-09 13:54
Mix doesn't have a custom watcher in this case. It's all webpack behind the scenes. 

I'm having trouble reproducing this. Can someone give me exact steps in a fresh Laravel app to see this error?

**Comment by wafs** [comment] 2017-08-10 02:48
I've narrowed down the problem, and this isn't a problem with laravel-mix per se, but webpack and specifically the watcher - is setting something in a global variable and it is getting overwritten by something else.

I was able to reproduce the problem by bringing in `axios` and `ExtractTextPlugin` and set up 

First time you run watch, everything is working fine, 

second time around, the watcher will recompile and `axios` will attempt to bring in utils 

```javascript
// from /node_modules/axios/lib/helpers/isURLSameOrigin.js
'use strict';

var utils = require('./../utils');

module.exports = (
  utils.isStandardBrowserEnv() ?
// etc
```

however it is overwritten by `/node_modules/css-loader/lib/css-base.js`

![image](https://user-images.githubusercontent.com/5717802/29151585-97d261bc-7dc5-11e7-8c9a-9f6c86dc3150.png)


From Chrome devtools dumping the utils obj to console: 
![image](https://user-images.githubusercontent.com/5717802/29151546-3d7edc4a-7dc5-11e7-94f2-694f22606a66.png)


```javascript

// import a list of modules into the list
list.i = function(modules, mediaQuery) {
	if(typeof modules === "string")
	modules = [[null, 
// etc
```


I managed to fix it with this ugliness inside the vue-loader : 

```javascript
test   : /\.vue$/,
        loader : 'vue-loader',
        options: {
          extractCSS: true,
          loaders   : { 
                scss: is_prod ? ExtractTextPlugin.extract({use:'css-loader!sass-loader',fallback:'vue-style-loader'}) : 'vue-style-loader!css-loader!sass-loader',
                sass: is_prod ? ExtractTextPlugin.extract({use:'css-loader!sass-loader?indentedSyntax',fallback:'vue-style-loader'}) : 'vue-style-loader!sass-loader?indentedSyntax',
                css : is_prod ? ExtractTextPlugin.extract({use:'css-loader',fallback:'vue-style-loader'}) : 'vue-style-loader!css-loader',
          },
```


Searching around, it seems to be linked to this : https://github.com/webpack/webpack/issues/5399

**Comment by JhumanJ** [comment] 2017-08-10 08:26
@wafs Could you me a bit more explicit about your fix (which file..etc.)? Thanks!

**Comment by JeffreyWay** [comment] 2017-08-11 14:25
Yeah this doesn't seem to be a Mix-specific issue. It's either directly webpack or the extract plugin. 

Giving this a close, since there's nothing I can directly do here to fix it.

**Closed by JeffreyWay** 2017-08-11 14:25 UTC

**Comment by maxonly** [comment] 2017-08-18 07:55
I have same error when i update my vue file，how to fix ? Thanks!

**Comment by bryandease** [comment] 2017-08-18 20:57
I can confirm that using that downgrading to `extract-text-webpack-plugin@2.1.2` solves the issue for me.

**Comment by maxonly** [comment] 2017-08-19 00:39
@bryandease But my webpack version is 3.5, it not match `extract-text-webpack-plugin@2.1.2`

![image](https://user-images.githubusercontent.com/7932853/29481838-c7f22504-84b8-11e7-8770-10d8ce83ef74.png)

**Comment by wjgilmore** [comment] 2017-08-31 12:43
I'm also experiencing this problem. @bryandease can you elaborate regarding how you downgraded extract-text-webpack-plugin to resolve it? I'm not quite sure how to override the mess of JS requirements. For instance I installed `extract-text-webpack-plugin@2.1.2` in my project's root package.json file but that didn't fix it. Is there another way to override the version of `extract-text-webpack-plugin` being used down the tree? Thank you!

**Comment by wadday** [comment] 2017-09-02 23:03
I am using Laravel 5.5 with Bulma CSS & Vuejs 2. 
I am also experiencing the same problem. but after I run artisan command to clear compile and then run composer dump-autoload and my issues got solved.
thank you.

**Comment by jonnywilliamson** [comment] 2017-09-04 12:36
Having the same issue at the moment.

It's only started happening recently. If I'm using 'npm run watch"  and change something in my global scss file and watch as mix recompiles everything, I'll get the above error as soon as I refresh my webpage on my app.

IF I happen to open say, one of my vue components and immediately save it (forcing npm watch to do a recompile) everything is fixed again.

It's a little annoying but that's what I'm doing at the moment to work around it.

**Comment by Daniesy** [comment] 2017-09-05 11:50
I managed to recreate it..kinda.

### Initial conditions: 
- .scss & .vue files that need to get compiled.
- package.json dependencies:
-- "axios": "^0.16.2",
-- "cross-env": "^5.0.1",
-- "laravel-mix": "^1.0",
-- "lodash": "^4.17.4",
-- "moment": "^2.18.1",
-- "vue": "^2.1.10",
-- "vue-i18n": "^7.2.0",
-- "vuejs-datepicker": "^0.9.11"

### Steps:
1. While having `npm run watch` on, make some changes to a .scss and save.
2. **Empty cache and hard reload**(refresh) the browser and see `Uncaught TypeError: utils.isStandardBrowserEnv is not a function` in the console.
3. Make some changes to a .vue file.
4. **Empty cache and hard reload**(refresh) the browser and see `Uncaught SyntaxError: Invalid or unexpected token`.
5. Wait a lil bit and try **Empty cache and hard reload**(refresh) again. Finally it will work ok.

### Note: 
- Laravel Mix seems very buggy in this new release. You'll get a js error (Unexpected end of input) if you refresh the browser right after the files are compiled. You have to wait a few seconds.

**Comment by ottz0** [comment] 2017-09-06 04:53
Same issue...I cant use npm watch whilst editing a sass file. I need to to npm run dev every time I change a sass file

**Comment by anthonyholmes** [comment] 2017-09-14 05:12
Adding `mix.version()` seemed to fix the issue for me

**Comment by tesis** [comment] 2017-09-15 18:55
I have the same issue.
Unfortunately, adding mix.version() triggers another error.

It's working fine with npm run dev and npm run hot.

**Comment by ItsLhoudini** [comment] 2017-10-16 21:40
Same here!

**Comment by xxRockOnxx** [comment] 2017-10-17 01:52
To me it happens only if I save `.scss` files. To fix it i'd just `ctrl+s` on a `.js` file.

**Comment by vyzaldysanchez** [comment] 2017-11-17 05:33
I also experienced this while changing my .scss styles !
