### ISSUE TITLE
Error after upgrading to 0.10.0

### ISSUE THREAD

**Issue by jakubkratina** [JeffreyWay/laravel-mix#717] opened 2017-04-18 15:00 UTC
- npm 4.2.0
- node v7.8.0
- laravel 5.4
- laravel mix 0.10.0

`package.json`

```
{
	"private": true,
	"scripts": {
		"dev": "npm run development",
		"development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --watch --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js",
		"watch-poll": "npm run watch -- --watch-poll",
		"hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --config=node_modules/laravel-mix/setup/webpack.config.js",
		"prod": "npm run production",
		"production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js"
	},
	"devDependencies": {
		"axios": "^0.16.1",
		"bootstrap-sass": "^3.3.7",
		"cross-env": "^3.2.3",
		"gulp": "^3.9.1",
		"jquery": "^3.1.1",
		"laravel-mix": "0.*",
		"lodash": "^4.17.4",
		"stylus": "^0.54.5",
		"stylus-loader": "^3.0.1",
		"vue": "^2.1.10"
	},
	"dependencies": {
		"rupture": "^0.6.2",
		"axios": "^0.15.3",
		"moment": "^2.17.1",
		"vuejs-datepicker": "^0.7.3"
	}
}

```

`webpack.mix.js`
```
let mix = require('laravel-mix');

mix.stylus('resources/assets/stylus/app.styl', '../resources/assets/css/app.css')
	.options({
		processCssUrls: false
	});

mix.sass('resources/assets/sass/bulma.sass', '../resources/assets/css/bulma.css')
	.options({
		processCssUrls: false
	});

mix.js([
	'resources/assets/js/app.js',
	'resources/assets/js/scroll.js',
	'resources/assets/js/navigation.js',
	'resources/assets/js/custom.js',
	'resources/assets/js/css.js',
	'resources/assets/js/numbers.js' // https://github.com/talmand/jquery-animate-numbers
], 'public/js/all.js');

mix.styles([
	'resources/assets/css/app.css',
	'resources/assets/css/bulma.css',
], 'public/css/app.css');

mix.scripts([
	'resources/assets/plugins/jquery.min.js',
	'resources/assets/plugins/bootstrap.min.js',
	'resources/assets/plugins/swiper.jquery.min.js',
	'resources/assets/plugins/lazysizes.js', // https://github.com/aFarkas/lazysizes
	// 'resources/assets/plugins/unveil.js',
	'resources/assets/js/header.js'
], 'public/js/header.js');

if (mix.config.inProduction) {
	mix.version();
}
```

Hello guys,

after upgrading and running `npm run production` I get:

```
npm run production

> @ production /Users/wise/Sites/tartaletka
> cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js

 95% emitting                                                                            

 DONE  Compiled successfully in 21195ms                                                                             4:59:04 PM


undefined:92
    throw new DefaultsError(msg, defs);
    ^
Error: 

npm ERR! Darwin 16.6.0
npm ERR! argv "/usr/local/Cellar/node/7.3.0/bin/node" "/usr/local/bin/npm" "run" "production"
npm ERR! node v7.8.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! @ production: `cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the @ production script 'cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the  package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --progress --hide-modules --config=node_modules/laravel-mix/setup/webpack.config.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs 
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls 
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/wise/.npm/_logs/2017-04-18T14_59_05_378Z-debug.log

```

It's really a general error, don't you know, where the problem could be? 

An error will be in the last `mix.scripts(` part. Is the syntax correct?

Thank you.

**Comment by jakubkratina** [comment] 2017-04-18 15:14
Even if I try to replace `mix.scripts` for `mix.combine` it doesn't work and throws the same error.

**Comment by jakubkratina** [comment] 2017-04-18 15:15
It's same like here: https://github.com/JeffreyWay/laravel-mix/issues/675

**Comment by JeffreyWay** [comment] 2017-04-18 19:03
Do you get this error when you run `npm run dev`? Is it exclusive to production mode?

**Comment by jakubkratina** [comment] 2017-04-18 19:12
It fails when the production mode only.

**Comment by JeffreyWay** [comment] 2017-04-19 20:00
Closing this, as it's a duplicate of #675.

**Closed by JeffreyWay** 2017-04-19 20:00 UTC
