### ISSUE TITLE
Source Maps not generating in dev

### ISSUE THREAD

**Issue by jfalotico** [JeffreyWay/laravel-mix#932] opened 2017-06-25 22:34 UTC
- Laravel Mix Version: #.#.# (`npm list --depth=0`) :   version "1.0.6"
- Node Version (`node -v`): 8.0.0
- NPM Version (`npm -v`): 4.2.0
- OS: osx 10.12.6

### Description:
Source maps not getting generated 

### Steps To Reproduce:
```

const mix = require('laravel-mix')

/*
 |--------------------------------------------------------------------------
 | Mix Asset Management
 |--------------------------------------------------------------------------
 |
 | Mix provides a clean, fluent API for defining some Webpack build steps
 | for your Laravel application. By default, we are compiling the Sass
 | file for the application as well as bundling up all the JS files.
 |
 */

mix
    .js('resources/assets/js/app.js', 'public/js')
    .js('resources/assets/js/public.js', 'public/js')
    .sass('resources/assets/sass/app.scss', 'public/css')
    .sass('resources/assets/sass/public.scss', 'public/css')
    .extract([
        'vue',
        'vuex',
        'brace',
        'axios',
        'jquery',
        'lodash',
        'hint.css',
        'nprogress',
        'pusher-js',
        'clipboard',
        'vue-router',
        'vuedraggable',
        'laravel-echo',
        'moment-timezone',
        'filesize-parser',
        'lodash-inflection',
        'moment-precise-range-plugin'
    ])
    .autoload({
        vue: 'Vue',
        lodash: '_',
        ace: 'brace',
        'pusher-js': 'Pusher',
        clipboard: 'Clipboard',
        jquery: ['$', 'jQuery']
    })
    .sourceMaps()
    .version()

if (!mix.inProduction()) {
    mix.browserSync({
        open: 'external',
        host: 'codepier.dev',
        proxy: 'codepier.dev',
        files: [
            'resources/views/**/*.php',
            'public/js/**/*.js',
            'public/css/**/*.css'
        ]
    })
}

```

output : 

npm run dev 

![image](https://user-images.githubusercontent.com/1637963/27520237-81b0f962-59d4-11e7-9cc6-e56d8db60e1f.png)

**Comment by kulek1** [comment] 2017-06-27 09:24
Try this: https://github.com/JeffreyWay/laravel-mix/issues/879#issuecomment-310749504

Use one of them: 
`inline-source-map` or `source-map`

**Comment by szachara** [comment] 2017-07-16 11:53
Hard to develop without scss source maps :/

**Comment by deftx** [comment] 2017-07-17 16:49
Can confirm this issue. When using devtool: 'source-map', JS source maps are generated. .map files for CSS are generated but are blank.

**Comment by JeffreyWay** [comment] 2017-07-25 14:37
Seems to be a duplicate of #879, so closing this one.

**Closed by JeffreyWay** 2017-07-25 14:37 UTC

**Comment by tiagofrancafernandes** [comment] 2020-07-26 20:17
I ressolv with this:
https://github.com/JeffreyWay/laravel-mix/issues/1793#issuecomment-454948555
