### ISSUE TITLE
Build error - Unexpected Token

### ISSUE THREAD

**Issue by liam-ot** [JeffreyWay/laravel-mix#2909] opened 2021-03-23 21:32 UTC
-   Laravel Mix Version: 6.0.13 (`npm list --depth=0`)
-   Node Version (`node -v`): v15.12.0
-   NPM Version (`npm -v`): 7.6.3
-   OS: 
Distributor ID: CentOS
Description:    CentOS Linux release 7.9.2009 (Core)

### Description:
running `npm run dev` `npm run watch` and `npm run production` cause this error

```
ERROR in ./node_modules/laravel-mix/src/Mix.js 18:20
Module parse failed: Unexpected token (18:20)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| class Mix {
|     /** @type {Mix|null} */
>     static _primary = null;
|
|     /**

webpack compiled with 1 error
npm ERR! code 1
npm ERR! path /home/bvcom/public_html
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bvcom/.npm/_logs/2021-03-23T21_29_36_293Z-debug.log
npm ERR! code 1
npm ERR! path /home/bvcom/public_html
npm ERR! command failed
npm ERR! command sh -c npm run development

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bvcom/.npm/_logs/2021-03-23T21_29_36_306Z-debug.log
```
### Steps To Reproduce:
here's my package.json file
```
{
    "private": true,
    "scripts": {
        "dev": "npm run development",
        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js",
        "watch": "npm run development -- --watch",
        "watch-poll": "npm run watch -- --watch-poll",
        "hot": "cross-env NODE_ENV=development node_modules/webpack-dev-server/bin/webpack-dev-server.js --inline --hot --disable-host-check --config=node_modules/laravel-mix/setup/webpack.config.js",
        "prod": "npm run production",
        "production": "cross-env NODE_ENV=production node_modules/webpack/bin/webpack.js --no-progress --config=node_modules/laravel-mix/setup/webpack.config.js"
    },
    "devDependencies": {
        "@inertiajs/inertia": "^0.8.5",
        "axios": "^0.19",
        "cross-env": "^7.0",
        "laravel-mix": "^6.0.13",
        "lodash": "^4.17.19",
        "postcss-import": "^14.0.0",
        "postcss-nesting": "^7.0.1",
        "resolve-url-loader": "^3.1.0",
        "tailwindcss": "^2.0.4",
        "vue": "^2.6.12",
        "vue-template-compiler": "^2.6.12"
    },
    "dependencies": {
        "n": "^7.1.0",
        "path": "^0.12.7",
        "stable": "^0.1.8"
    }
}
```
run `npm install` and then try running `npm run dev` should reproduce this error in a fresh laravel project

**Comment by thecrypticace** [comment] 2021-03-23 21:35
Two things:
1. I'd use the mix CLI for your npm scripts instead of `cross-env` + `node_modules/webpack/bin/webpack.js` if possible.
2. Based on the error it appears that Mix is being included in your compiled build which isn't correct.

**Comment by liam-ot** [comment] 2021-03-23 21:37
@thecrypticace I apologize, my familiarity with this all is low, can you please be a bit more in depth in your answer? i appreciate the help

**Comment by thecrypticace** [comment] 2021-03-23 21:38
This error:
> You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders

Is because mix is being compiled by babel when it shouldn't be. Can you provide your app.js file. Or better yet, a reproduction repo?

**Comment by liam-ot** [comment] 2021-03-23 21:38
@thecrypticace 
```
const mix = require('laravel-mix')
const path = require('path')

mix.js('./app.js', '../../public/js')
  .webpackConfig({
    output: { chunkFilename: 'js/[name].js?id=[chunkhash]' },
    resolve: {
      alias: {
        vue$: 'vue/dist/vue.runtime.esm.js',
        '@': path.resolve('resources/js'),
      },
    },
  })

```

**Comment by thecrypticace** [comment] 2021-03-23 21:41
Yeah that file is correct however your webpack.mix.js file should't be in the same directory as your code which is likely the issue here. It should be at your project root. My guess is that app.js has a contextual import (something like `require(`${something}.js`) which causes all files in the folder to be included in the bundle.

A reproduction repo would help here.

**Comment by liam-ot** [comment] 2021-03-23 21:44
what is a reproduction repo?

**Comment by liam-ot** [comment] 2021-03-23 21:47
web root is public_html/public and the webpack.mix.js is in public_html

there is no contextual import in app.js, i shared the whole of app.js in my last comment

**Comment by liam-ot** [comment] 2021-03-23 21:53
i changed my app.js to this one taken from the Inertiajs PingCRM git repo
```
import { InertiaApp } from '@inertiajs/inertia-vue'
import Vue from 'vue'

Vue.use(InertiaApp)

const app = document.getElementById('app')

new Vue({
  render: h => h(InertiaApp, {
    props: {
      initialPage: JSON.parse(app.dataset.page),
      resolveComponent: name => require(`./Pages/${name}`),
    },
  }),
}).$mount(app)
```

and now the errors have changed to these:
```
ERROR in ../node_modules/axios/lib/defaults.js 21:20-27
Module not found: Error: Can't resolve 'process/browser' in '/home/bvcom/node_modules/axios/lib'

ERROR in ./resources/js/Pages/Home/Index.vue 1:0
Module parse failed: Unexpected token (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> <template>
|       <div>
|               <h1>Brite Visual Products</h1>

webpack compiled with 2 errors
npm ERR! code 1
npm ERR! path /home/bvcom/public_html
npm ERR! command failed
npm ERR! command sh -c cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress --config=node_modules/laravel-mix/setup/webpack.config.js

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bvcom/.npm/_logs/2021-03-23T21_52_49_561Z-debug.log
npm ERR! code 1
npm ERR! path /home/bvcom/public_html
npm ERR! command failed
npm ERR! command sh -c npm run development

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/bvcom/.npm/_logs/2021-03-23T21_52_49_574Z-debug.log
```

**Comment by liam-ot** [comment] 2021-03-23 21:57
ignore the last comment if you saw it before i deleted it about changing the app.js file, it was only causing more issues

**Comment by liam-ot** [comment] 2021-03-23 22:01
here's that min repo, i think

lmk if you need more files

https://github.com/liam-ot/min-rep-repo

**Comment by liam-ot** [comment] 2021-03-23 22:42
have changed one line in webpack.mix.js to now include 
```
.vue({ version: 2 })
```
in between `mix.js(...)` and `.webconfig(...)` and updated the min rep repo

**Comment by liam-ot** [comment] 2021-03-23 23:14
i have seen this exact error now 4 times in separate places all occuring due to the line `static _primary = null` in their `node_modules/laravel-mix/src/Mix.js` file however they all claim to resolve the error by updating to a newer version of nodejs which makes me assume there is some compatibility issue with node v15.12.0, i have downgraded to v14.16.0 for now but the error persists

**Comment by thecrypticace** [comment] 2021-03-23 23:58
1. Your app.js is incorrect. It should not include laravel-mix.
2. The `require(`./Pages/${name}`)` import is a context import and will cause files bundled in the same directory to get included. Please put your JS in a folder separate from laravel-mix.  You can look at the laravel repo for an example: https://github.com/laravel/laravel

As this is not an issue with mix itself I'm closing this issue. If you have further problems I suggest you ask on something like the Laracasts forum.

**Closed by thecrypticace** 2021-03-23 23:58 UTC
