### ISSUE TITLE
environment variables inside "webpack.mix.js" doesnt work anymore

### ISSUE THREAD

**Issue by ctf0** [JeffreyWay/laravel-mix#1155] opened 2017-09-01 07:03 UTC
- Laravel Mix Version: v1.4.2
- Node Version v8.4.0
- NPM Version v5.3.0
- OS: OSX 10.11.6

### Description:
using an evn variable no longer works on assets compilation, on older version of mix **0.11.4** it was working correctly.

### Steps To Reproduce:

- create a new folder and name it something like "resources/bulma/xxx.scss"
- make an env var equal to that name "MIX_MM_FRAMEWORK=bulma"
- compile against the env var name
```js
mix.sass('resources/' + process.env.MIX_MM_FRAMEWORK + '/xxx.scss', 'public/assets/vendor/style.css')
    .version()
```

https://github.com/JeffreyWay/laravel-mix/issues/1096

**Comment by dabernathy89** [comment] 2017-09-01 15:17
duplicate of #1143

**Closed** 2017-09-01 15:46 UTC

**Comment by dabernathy89** [comment] 2017-09-01 16:22
@ctf0 BTW it looks like all you need to do is use the `dotenv` package yourself (already installed by Mix). For example, here's how i'm using it to define the Browsersync proxy URL for a WordPress theme:

```
let mix = require('laravel-mix');
require('dotenv').config();
 
let proxy_url = process.env.BROWSERSYNC_PROXY_URL || 'local.wordpress.dev';

// .. your mix configuration here...
    .browserSync({
        proxy: proxy_url,
    });
```

**Comment by ctf0** [comment] 2017-09-02 07:22
@dabernathy89 focken AWESOME, many thanx.

**Comment by josegus** [comment] 2018-12-17 22:59
I could i never realize that just using process.env.APP_URL works! I'm using laravel-mix v4, no need to require dotenv

**Comment by austinmukumoto** [comment] 2024-07-25 01:15
Im using laravel 9 and Mix 6.0 i already tried this but no effect may i know if theres another solution. thank you so much

**Comment by cairomadr** [comment] 2025-02-13 01:26
Did anyone find a fix
