### ISSUE TITLE
Can't get vue sass modules to work

### ISSUE THREAD

**Issue by brianrlewis** [JeffreyWay/laravel-mix#2370] opened 2020-04-08 23:05 UTC
-   Laravel Mix Version: 5.0.4
-   Node Version: v12.14.1
-   NPM Version: 6.13.4
-   OS: Windows 10

### Description:

I can't get my assets to compile properly when using vue sass modules. I either get an error during compilation or the scss within the vue component is treated as standard scss as opposed to a scss module that should only apply to the component in which it is defined.

My current project uses `laravel-mix v3.0.0` and I am trying to upgrade to `v5.0`. With `v3.0.0` I do not have to add any configuration to `webpack.mix.js`, both css and sass modules work fine right out of the box. Apparently this is no longer the case as of `v4.0`. I see in the `v4.0` release notes that the sass dependencies are no longer included by default but there is no mention of webpack configuration.

I created a fresh, minimal laravel 7.x installation to reproduce the problem and rule out any causes related to my existing project.

Here is the link to the repo:
https://github.com/brianrlewis/laravel-vue-sass-modules-problem

I've tried many different webpack configurations inside `webpack.mix.js` without any success.

### Steps To Reproduce:

1. Clone this repo: https://github.com/brianrlewis/laravel-vue-sass-modules-problem
2. npm install
3. npm run dev
4. composer install
5. php artisan serve

When you get to step 3 you should get this error:

```
ERROR in ./resources/js/WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true& (./node_modules/css-loader!./node_modules/vue-loader/lib/loaders/stylePostLoader.js!./node_modules/postcss-loader/src??ref--6-2!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./node_modules/vue-style-loader!./node_modules/sass-loader/dist/cjs.js!./node_modules/vue-loader/lib??vue-loader-options!./resources/js/WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true&)
Module build failed (from ./node_modules/sass-loader/dist/cjs.js):
SassError: expected "{".
  ╷
4 │ var content = require("!!../../node_modules/sass-loader/dist/cjs.js!../../node_modules/vue-loader/lib/index.js??vue-loader-options!./WhyYouNoWork.vue?vue&type=style&index=0&lang=scss&module=true&");
```

If you uncomment this at the bottom of `webpack.mix.js` you will get a different error.
`//   .sass('resources/sass/app.scss', 'public/css');`

To get to steps 4 and 5 you can comment out the following in `webpack.mix.js` which will allow a successful build.

```
            {
                test: /\.scss$/,
                use: [
                  'vue-style-loader', // 'style-loader' doesn't work either
                  'css-loader',
                  'sass-loader'
                ],
            }
```

After you load the site you can see that the sass inside `resources/js/WhyYouNoWork.vue` gets applied to the entire site globally as opposed to only styling `<div :class="$style.wrapper">`. I'm assuming this is simply because `sass-loader` has to be added to the webpack config in order for this to work.

Using css modules works fine, just not scss modules.

Any ideas on how to get this to work? 

I've tried everything listed here, plus a dozen other sass-loader config variations.
https://vue-loader.vuejs.org/guide/pre-processors.html

**Comment by xaru123** [comment] 2020-05-15 19:58
Hi! I have this problem too. Do you find a solution?

**Comment by brianrlewis** [comment] 2020-05-19 04:00
@xaru123 No, unfortunately I have not found a solution to this problem yet. Still anxiously waiting for some assistance.

**Comment by rafern** [comment] 2020-05-27 10:39
The problem is that css-loader doesn't have modules enabled and there is no option in laravel-mix to enable it. I made a PR at the end of march (https://github.com/JeffreyWay/laravel-mix/pull/2358) to expose this option, but the maintainers seem to be busy with porting to Webpack 5 so it hasn't been merged, or it might not be merged at all since this feels more like a hack than a solution.

You can use that fork for now and add an option `enableCssModules` to true in `mix.options`. For example, add this to `webpack.mix.js`:
```
mix.options({
    enableCssModules: true,
});
```

**Comment by brianrlewis** [comment] 2020-05-29 04:37
Thanks @rafern, this works beautifully.

**Comment by brianrlewis** [comment] 2020-05-29 06:12
@rafern It appears that there is still an issue that needs to be worked out. When I use your solution and set `enableCssModules: true` I am able to use sass modules inside vue single file components. However it appears that the use of css/sass modules is globally enforced across all vue components, regardless of whether the `module` option is specified in the style tag or not.

This happens regardless of whether the style block is using css or scss.

For example the following:

```
<style>
.my-element {
}
</style>
```

Would become this after the build:

```
<style>
._2KzbwyDZ9CNp0KCgg5PKgQ {
}
</style>
```

When it should only do that if you specify `<style module>`

Any ideas on how to get laravel-mix to respect the `module` option inside vue components?

**Comment by brianrlewis** [comment] 2020-07-30 17:47
Since we are still waiting on a fix I am bumping this issue so that it is not automatically closed

**Comment by beamsies** [comment] 2020-08-30 21:20
Any updates?

**Comment by beamsies** [comment] 2020-08-30 22:17
@brianrlewis Were you able to get .scss modules working in the vue <style> tags?

**Comment by brianrlewis** [comment] 2020-08-31 17:32
@beamsies We're still waiting for an official fix but in the meantime rafern fixed the problem in a [forked repo](https://github.com/rafern/laravel-mix) (see pull #2358).

**Closed** 2020-10-23 14:36 UTC
